### ISSUE TITLE
TTL during import

### ISSUE THREAD

**Issue by abalakersky** [barnybug/cli53#102]
While doing migration for a customer I noticed that using import command with cli53 sets all A and CNAME records to a TTL of 0, which is too short. Using rrcreate command doesn't do that, even if you don't specify TTL with -x. With rrcreate record is created with 86400 TTL, however during import it is set to 0, unless every record line in the zone file has TTL value added.
Shouldn't import command default to something larger then 0 for TTL? For example reading main TTL for the zone file and using that as a base for all RR?

Thanks,

**Comment by barnybug** [comment]
According to wikipedia a globally defined $TTL would be used in this case (which cli53 obeys). For the situation where ttl is neither defined on a record, nor at the global level the behaviour seems ill-defined, and indeed cli53 behaves as you describe, which as you say doesn't seem ideal.

I don't think the situation would commonly be encountered, and there is a workaround (correctly define $TTL at the global level), but happy to accept a patch...

**Comment by abalakersky** [comment]
The problem is that there is a global TTL defined in the zone file. However during import it is being ignored.
I will send an example zone file tomorrow, when I get to the office. Global TTL is always ignored, never being used during import.

Thanks,
Alex

On Aug 30, 2015, at 17:46, Barnaby Gray <notifications@github.com<mailto:notifications@github.com>> wrote:


According to wikipedia a globally defined $TTL would be used in this case (which cli53 obeys). For the situation where ttl is neither defined on a record, nor at the global level the behaviour seems ill-defined, and indeed cli53 behaves as you describe, which as you say doesn't seem ideal.

I don't think the situation would commonly be encountered, and there is a workaround (correctly define $TTL at the global level), but happy to accept a patch...

-

**Comment by barnybug** [comment]
In your zones you are definitely setting "$TTL ..."?
see: http://www.zytrax.com/books/dns/apa/ttl.html

**Comment by abalakersky** [comment]
In all of my zones the SOA record contains the default TTL. We don't have separate TTL entry. Never needed is since Bind is nice enough to read SOA record. So cli53 does read a separate TTL entry?

Sent from my mobile device.
Please excuse any typing issues and shortness of speech.

On Aug 31, 2015, at 05:16, Barnaby Gray <notifications@github.com<mailto:notifications@github.com>> wrote:


In your zones you are definitely setting "$TTL ..."?
see: http://www.zytrax.com/books/dns/apa/ttl.html

-
