### ISSUE TITLE
export of public private zones

### ISSUE THREAD

**Issue by mylesparker** [barnybug/cli53#104]
I read the docs on creating public private zones

To manage zones that have both a private and a public zone, you must specify the zone ID instead the domain name, which is ambiguous. This is the 13 character ID after '/hostedzone/' you can see in the output to 'cli53 list'. eg::

$ cli53 rrcreate ZZZZZZZZZZZZZ name A 127.0.0.1

but on attempting to do the same with export I get the following errors:
cli53 export Z2Q4VKANW5QUMK --file scratch.bk
usage: cli53 [-h] [-d] [--logconfig LOGCONFIG]
             {list,info,xml,export,import,instances,create,delete,rrcreate,rrdelete,rrpurge,rrlist}
             ...
cli53: error: unrecognized arguments: --file scratch.bk

How can I export based on the zone ID?

**Comment by barnybug** [comment]
--file isn't an argument.
