### ISSUE TITLE
Install instructions for Amazon Linux [Non-Issue but may help]

### ISSUE THREAD

**Issue by ChrisDean** [barnybug/cli53#105]
Not sure if you'd want to use the wiki for something like this or put it into your readme but these might be of use of use to someone trying to use this on Amazon Linux for the first time (presuming python not already installed):

1.) Install python and pip
$> yum install python27 python27-pip

2.) Install cli53
$> pip-2.7 install cli53

3.) cli53 is installed to /usr/local/bin which is not in the default path for bash on amazon linux so you'll need to call it directly (unless you add it to your path or alias it in .bashrc)
$> /usr/local/bin/cli53 --help

**Comment by barnybug** [comment]
I've expanded on the instructions. Thanks!
