### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by rtkmhart** [barnybug/cli53#106]
Can we get a new release published to pypi? I'm particularly interested in https://github.com/barnybug/cli53/commit/5add20357115fb514b0e0a9c18c3d3e2e6152e5b since I've hit that a few times. Looking forward to 0.4.5. If I can help in any way let me know.

thanks!

**Comment by barnybug** [comment]
Good point - thanks for the reminder. I went one better and called the new release 0.5.0 :-)

**Comment by rtkmhart** [comment]
Thank you! Appreciate your work on this.
