### ISSUE TITLE
Backup Creates duplicate records when there are > 100 Entries

### ISSUE THREAD

**Issue by pcorliss** [barnybug/cli53#112]
When backing up and then restoring we received an error about a duplicate record in the bind file. It appeared around line 104,105 of the file, implying a pagination issue with many records. We manually deleted the line and were able to recover.

```
./cli53-linux-amd64 export example.com > example.com.bind.bkp
./cli53-linux-amd64 import --file example.com.bind.bkp --replace example.com
```

**Comment by barnybug** [comment]
Hi, thanks for the report - would it be possible to attach a minimal zone file that reproduces the issue?

**Comment by barnybug** [comment]
Ah, it's ok - I've found a case if there's multiple records under the same name with different record types / identifiers - would this match your case?
