### ISSUE TITLE
Export throws exception

### ISSUE THREAD

**Issue by brendabell** [barnybug/cli53#114]
I downloaded the Mac binaries. When I try to run it, I get the following error:

/usr/local/bin/cli53: line 1: syntax error near unexpected token `<'
/usr/local/bin/cli53: line 1: `<html><body>You are being <a href="https://github-cloud.s3.amazonaws.com/releases/1166061/6abd0ef2-729b-11e5-8d50-34119e2a051b?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential={removed-my-credentials}%2F20151019%2F{removed-my-zone}%2Fs3%2Faws4_request&amp;X-Amz-Date=20151019T232046Z&amp;X-Amz-Expires=300&amp;X-Amz-Signature={removed-signature}&amp;X-Amz-SignedHeaders=host&amp;actor_id=0&amp;response-content-disposition=attachment%3B%20filename%3Dcli53-mac-amd64&amp;response-content-type=application%2Foctet-stream">redirected</a>.</body></html>'

This was in response to cli53 export {my-domain-name}.

**Comment by barnybug** [comment]
It looks like you haven't downloaded the binary - perhaps a web page redirecting to the download page?
Check you're saving the binary itself.

**Comment by barnybug** [comment]
Closing.
