### ISSUE TITLE
"--replace" is missing from Windows build 0.6.2

### ISSUE THREAD

**Issue by deniskami** [barnybug/cli53#116]
Hello,

Thanks for such great tool!!!

It looks like 'rrcreate --replace" is not working because "--replace" option is missing from the Windows build

>cli53 -v
cli53 version 0.6.2

-----------------------
>cli53 rrcreate
NAME:
   cli53 rrcreate - create a record

USAGE:
   cli53 rrcreate [command options] zone record

OPTIONS:
   --debug, -d          enable debug logging
   --wait               wait for changes to become live
   --identifier, -i     record set identifier (for routed records)
   --failover           PRIMARY or SECONDARY on a failover routing
   --health-check       associated health check id for failover PRIMART
   --weight "0"         weight on a weighted routing
   --region             region for latency-based routing
   --country-code       country code for geolocation routing
   --continent-code     continent code for geolocation routing

-------
>cli53 rrcreate --replace -d xxxxxx.net "www 600 A 22.22.22.22"
Incorrect Usage.

**Comment by barnybug** [comment]
It was added since 0.6.2. I've made a new release.
