### ISSUE TITLE
Can cli53 be used to create a private zone?

### ISSUE THREAD

**Issue by comptonqc** [barnybug/cli53#118]
I'd like to populate a Route 53 zone with some records that should be available only to machines within a VPC. Route 53 [supports this now](https://aws.amazon.com/blogs/aws/route-53-update-private-dns-more/), but I can't figure out how to create such a zone with cli53. Is it possible? If so, how would I do it?

**Comment by barnybug** [comment]
The creation step you'd need to do once off with route53, but after that cli53 can be used with the created zone.

**Comment by comptonqc** [comment]
Ok, thanks.
