### ISSUE TITLE
Add instances command

### ISSUE THREAD

**Issue by frederic-joventures** [barnybug/cli53#119]
just tried the go version and the instances command is missing. is there a replacement for that ? 

tx

**Comment by barnybug** [comment]
no, not fully caught up on features (yet!). Suggest sticking with the python version if you need this functionality.

**Comment by frederic-jomedia** [comment]
tx for the info. I will stick with the python version for now. Is it a feature that you want to add to the go version ?

**Comment by barnybug** [comment]
sure

**Comment by barnybug** [comment]
Let's keep the issue open as a placeholder.

**Comment by gabrielR0** [comment]
+1 on this feature. Maybe in 0.8 ?

**Comment by barnybug** [comment]
Fixed in cli53@0.8.5

**Comment by frederic-joventures** [comment]
Wow tx a lot you make my day !!!!
