### ISSUE TITLE
Unable to go get cli53 on OS X El Capitan

### ISSUE THREAD

**Issue by teran-mckinney** [barnybug/cli53#120]
Hi,

Using Go 1.5.1 installed via Brew, I get the following when I `go get` cli53.

```
$ go get github.com/barnybug/cli53
# github.com/barnybug/cli53
golang/src/github.com/barnybug/cli53/util.go:40: cannot use &config (type *aws.Config) as type client.ConfigProvider in argument to route53.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
```

This seems to be related: https://github.com/mitchellh/packer/issues/2890

Let me know what I should try next, or if I can provide any more details.

Thank you,
Teran

**Comment by barnybug** [comment]
Does it make a difference if you:
export GO15VENDOREXPERIMENT=1
Before go getting?

**Comment by josegonzalez** [comment]
@barnybug I had the same issue on Yosemite, and using that `export` command seems to allow the go get to run.
