### ISSUE TITLE
CLI53 Export and CNAME record last

### ISSUE THREAD

**Issue by cpkwebsolutions** [barnybug/cli53#123]
Hi

I encountered a strange issue with cli53 version 0.6.4, which could possibly be a bug.  Essentially, I exported a zone with a CNAME record appearing last and no domain was included.  ie

'www  14400 IN CNAME'

When I tried to import (--replace) the zone file after making changes, I received the following error:

"Error: InvalidChangeBatch: Invalid Resource Record: FATAL problem: DomainNameEmpty encountered at 
        status code: 400, request id: 06e554a7-8670-11e5-a661-730a6665cc78"

I've confirmed that:

1.  the record is correctly defined via the AWS console
2.  nothing I'm doing is mangling the file (it happens if I do cli53 export and then immediately follow up with cli53 import, having never opened the file)
3.  adding the domain to the CNAME record fixes the problem

Kind regards

Paul

**Comment by barnybug** [comment]
Thanks for reporting the issue. Woops, I can see the change that introduced it too. For now you can workaround the issue by using the -f flag on export to export full names (cli53 export -f ...).
