### ISSUE TITLE
Cannot create a CNAME to an ALIAS

### ISSUE THREAD

**Issue by emayssat-ms** [barnybug/cli53#129]
I would like to do the equivalent of this
aws --region us-west-1 --profile 7009 --output json route53 change-resource-record-sets --hosted-zone-id XXXXXXX --change-batch file://./zones.d/change_batch.json

$ cat change_batch.json
{
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "proxy-rc-vpc.xxxxxxxx.com",
        "Type": "CNAME",                                            # <--- Not a A record!
        "AliasTarget": {
          "HostedZoneId": "XXXXXXXXX",
          "DNSName": "pnr-proxy-001.xxxxx.com",
          "EvaluateTargetHealth": "false"
        }
      }
    }
  ]
}

The final record is a CNAME on an ALIAS.
But I can't or at least cannot find a way even by looking at the code
 $(CLI53) rrcreate --wait --replace $(HOSTED_ZONE) proxy-rc-vpc ALIAS '$(HOSTED_ZONE_ID) pnr-proxy-$(DEPLOY_ID).$(HOSTED_ZONE)'

Please also update the github docs with up to date examples.

**Comment by barnybug** [comment]
Hi - have you tried following the example for an ALIAS in the README?

**Comment by barnybug** [comment]
ah, I see the example is for an elb alias.
For a CNAME alias, take a look at the tests (alias3.txt specifically).
The format should be something like:
cli53 rrcreate --wait --replace domain 'alias	AWS	ALIAS	CNAME www target false'

**Comment by emayssat-ms** [comment]
$ cli53 rrcreate --wait --replace menlosecurity.com 'proxy-rc-vpc AWS ALIAS CNAME pnr-proxy-001 $self false'
usage: cli53 rrcreate [-h] [-x TTL] [-w WEIGHT] [-i IDENTIFIER]
                      [--region REGION] [--failover FAILOVER] [-r] [--wait]
                      [--dump]
                      zone rr {A,AAAA,CNAME,SOA,NS,MX,PTR,SPF,SRV,TXT,ALIAS}
                      values [values ...]
cli53 rrcreate: error: too few arguments

**Comment by barnybug** [comment]
It looks like you're using an old version. Remove this and install the latest.
