### ISSUE TITLE
AWS Alias record export

### ISSUE THREAD

**Issue by travmi** [barnybug/cli53#131]
Is anyone else having problems with AWS Alias records showing "@self".

This happens when running: cli53 export --full mydomain.com

```
www.mydomain.com.        86400   AWS     ALIAS   A @ $self false
```

**Comment by barnybug** [comment]
"   --full, -f	export prefixes as full names"
So it's behaving as documented at least, even if it's not as you're expecting. Perhaps you could explain your use case to me?

**Comment by travmi** [comment]
So looking at this more there are actually a couple differences i'm seeing between the Go version and the Python version. Go changes the TTL to 86400 and outputs '@self' for the Value. Python version actually shows my TTL and correct Value.

Python Version
```
mydomain.com. 600 AWS ALIAS Z6WVYL1QF0XNV cmpsystem.com.
```

Go Version
```
mydomain.com.     86400   AWS     ALIAS   A @ $self false
```

**Comment by barnybug** [comment]
Interesting, the TTL of an ALIAS record is actually meaningless - it will always use the target TTL, and you'll notice there's not actually a way to set the TTL in the Amazon Web Console (when you select Alias: Yes, the TTL selection disappears).

**Comment by barnybug** [comment]
Regarding the python version, it's broken in a number of ways around aliases, so I wouldn't regard this as model behaviour. :-)
(For example it could never handle anything other than A ALIAS records)

**Comment by travmi** [comment]
So in the Go version the "@ $self" means it's pointing to the target ALIAS? So it won't show the Alias Hosted Zone ID like the Python version does?

**Comment by barnybug** [comment]
So in DNS terminology "@" always means apex/origin of the domain (ie the root).
$self is cli53 'terminology' for the same Hosted Zone ID.

The python version would always export the Hosted Zone ID, which isn't much use, given the user has no control over this ID (it's generated by Amazon). If you accidentally removed a zone and wanted to recreate it from the export, then the export would be invalid because you're new zone would have a different Zone ID.

I'm thinking --full behaviour should probably leave @ expanded as the absolute domain, particularly if you convince me. :-)

As for the Zone ID vs '$self'. Not sure on this one - neither behaviour is right/wrong as such - so was trying to understand in what situation the current behaviour it's not working for your use case.

**Comment by travmi** [comment]
When attempting to import the zone file AWS errors out with a zone file produced by: cli53 export mydomain.com. Due the export containing 'AWS' as a record type.

**Comment by barnybug** [comment]
Sorry, to clarify you're attempting to 'cli53 import' the file generated by cli53 export', but it is erroring? Could you possibly provide reproduction steps?

**Comment by travmi** [comment]
I apologize for extended issues I'm having. Working through this more I'm at a separate issue.

I created a domain and added various records. Performed "cli53 export mydomain.com"

Zone File
```
$ORIGIN mydomain.com.
@       900     IN      SOA     ns-905.awsdns-49.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
@       300     IN      A       1.1.1.1
@       172800  IN      NS      ns-905.awsdns-49.net.
@       172800  IN      NS      ns-382.awsdns-47.com.
@       172800  IN      NS      ns-1677.awsdns-17.co.uk.
@       172800  IN      NS      ns-1061.awsdns-04.org.
something       300     IN      A       4.2.2.2
test    3600    IN      A       8.8.8.8
this-here       86400   AWS     ALIAS   A @ $self false
```

I then delete the domain in the AWS console and attempt to restore the domain using cli53.

```
# cli53 create mydomain.com
Created zone: 'mydomain.com.' ID: '/hostedzone/Z2ZLGCD05PREW6'
# cli53 import --file mydomain.com.zone mydomain.com
Error: InvalidChangeBatch: Tried to create an alias that targets mydomain.com., type A in zone Z2ZLGCD05PREW6, but that target was not found
        status code: 400, request id: b322b91d-a060-11e5-8d20-f3671dc5bf41
```

I then remove the following from the exported zone file.
```
@       300     IN      A       1.1.1.1
```

Then manually create an "A" record for mydomain.com and attempt to import the rest of the records from the zone file.

```
# cli53 import --file mydomain.com.zone mydomain.com
8 records imported (3 changes / 3 additions / 0 deletions)
```

**Comment by barnybug** [comment]
ok, thanks. I've opened a new issue to log this.
