### ISSUE TITLE
Cannot import an ALIAS and the target record simultaneously

### ISSUE THREAD

**Issue by barnybug** [barnybug/cli53#133]
Refs #131 - thanks @travmi for reporting this issue. The tests don't currently test this case they import the target, then import the alias as separate steps.

I created a domain and added various records. Performed "cli53 export mydomain.com"

Zone File
```
$ORIGIN mydomain.com.
@       900     IN      SOA     ns-905.awsdns-49.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
@       300     IN      A       1.1.1.1
@       172800  IN      NS      ns-905.awsdns-49.net.
@       172800  IN      NS      ns-382.awsdns-47.com.
@       172800  IN      NS      ns-1677.awsdns-17.co.uk.
@       172800  IN      NS      ns-1061.awsdns-04.org.
something       300     IN      A       4.2.2.2
test    3600    IN      A       8.8.8.8
this-here       86400   AWS     ALIAS   A @ $self false
```

I then delete the domain in the AWS console and attempt to restore the domain using cli53.

```
# cli53 create mydomain.com
Created zone: 'mydomain.com.' ID: '/hostedzone/Z2ZLGCD05PREW6'
# cli53 import --file mydomain.com.zone mydomain.com
Error: InvalidChangeBatch: Tried to create an alias that targets mydomain.com., type A in zone Z2ZLGCD05PREW6, but that target was not found
        status code: 400, request id: b322b91d-a060-11e5-8d20-f3671dc5bf41
```

I then remove the following from the exported zone file.
```
@       300     IN      A       1.1.1.1
```

Then manually create an "A" record for mydomain.com and attempt to import the rest of the records from the zone file.

```
# cli53 import --file mydomain.com.zone mydomain.com
8 records imported (3 changes / 3 additions / 0 deletions)
```

**Comment by yshollander-selerity** [comment]
Please count me in as someone bitten by this functionality.  I had to split up the export file, and import it in sections, so that any record the AWS ALIAS records depended on were already in the zone.  All good now.  

Thank you for a very useful tool!
