### ISSUE TITLE
Add support for sts:assumerole/source_profile

### ISSUE THREAD

**Issue by geekifier** [barnybug/cli53#135]
In an MSP setting we often interact with many AWS client accounts. In order to streamline management of the account, we set up an IAM role in each client's account, which we then can temporarily 'assume' using our IAM credential.

See: https://blogs.aws.amazon.com/security/post/Tx2Q5SSG3SFRRHO/How-to-Use-External-ID-When-Granting-Access-to-Your-AWS-Resources.

When attempting to use cli53 with a --profile using this functionality, it results in the following error:

Error: SharedCredsAccessKey: shared credentials <PROFILENAME> in /Users/<USER>/.aws/credentials did not contain aws_access_key_id.

My ~/.aws/config:

[default]
output = json
region = us-east-1
[profile PROFILENAME]
source_profile = default
role_arn = arn:aws:iam::SECRET:role/SECRET-sts
region = us-east-1

In ~/.aws/credentials, the 'default' profile has the credentials for _my_ IAM User, in _our_ AWS Account (not client's).

As you can see, the credential file does not contain an access key for that specific profile, because it simply sources the default profile (using source_profile), which then uses the assumes the sts:assumerole function.

All of the native AWS CLI tools work natively with this, and it would be great if cli53 would too! I realize this is not a super widespread problem, and appreciate anyone who would be willing to look into this.

**Comment by barnybug** [comment]
This functionality would be dependent on the upstream library cli53 uses: https://github.com/aws/aws-sdk-go I think it'd worth inquiring there if there is support for this.

**Comment by barnybug** [comment]
To answer my own question - no it doesn't appear to be supported:
https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/shared_credentials_provider.go#L78

Please file a bug upstream and link this one to it.

**Comment by geekifier** [comment]
Thanks for looking into it. Filed a feature request upstream: https://github.com/aws/aws-sdk-go/issues/472.

**Comment by barnybug** [comment]
Looks like upstream issue has been closed, so I'm going to assume this is resolved.

**Comment by cjoneskinja** [comment]
If this is resolved, then what is the right way to do it? I've got it working through the aws cli but am struggling to do the same thing in cli53.

**Comment by cjonesunivision** [comment]
@joshuabaird I worked around it by storing the temporary keys that sts assume role creates into the .aws/credentials file. After that, cli53 is able to work with it.
