### ISSUE TITLE
compile cli53

### ISSUE THREAD

**Issue by emayssat-ms** [barnybug/cli53#136]
I am trying to install cli53 from source.
How to do that? I understand that go is a dependency.
I am on ubuntu14.04 and go doesn't have the required options.
I also noticed that there are many go dependencies, how do I install them?

Installation directive (even is simple) would be welcome in the README.md.

Best.

~/workspaces/github/cli53
emayssat@xps13 $ make
go install ./cmd/cli53
../../../go/src/pkg/github.com/barnybug/cli53/main.go:6:2: cannot find package "github.com/codegangsta/cli" in any of:
	/home/emayssat/go/src/pkg/github.com/codegangsta/cli (from $GOROOT)
	($GOPATH not set)
../../../go/src/pkg/github.com/aws/aws-sdk-go/aws/credentials/shared_credentials_provider.go:8:2: cannot find package "github.com/go-ini/ini" in any of:
	/home/emayssat/go/src/pkg/github.com/go-ini/ini (from $GOROOT)
	($GOPATH not set)
../../../go/src/pkg/github.com/aws/aws-sdk-go/aws/awsutil/path_value.go:9:2: cannot find package "github.com/jmespath/go-jmespath" in any of:
	/home/emayssat/go/src/pkg/github.com/jmespath/go-jmespath (from $GOROOT)
	($GOPATH not set)
make: *** [install] Error 1

**Comment by barnybug** [comment]
Hi - the instructions are all there in the README: https://github.com/barnybug/cli53/#building-from-source
You don't mention what version of go you are using, but I would suspect this is not 1.5.
You might be better to stick to the pre-built binaries (they're built by a third-party service travis-ci, direct from the sources, so you can trust them!).
