### ISSUE TITLE
Add back the previously supported '--ttl' option

### ISSUE THREAD

**Issue by lso-rf** [barnybug/cli53#137]
Love the new version!  Unfortunately, in the new Go version, you don't have the '--ttl' option, which I have been using in your Python version.  Would it be possible to restore this functionality?  Thanks.

**Comment by barnybug** [comment]
Hi - thanks for the kind words! The TTL value is part of the record as passed to rrcreate now, see A record examples in: https://github.com/barnybug/cli53/#getting-started
