### ISSUE TITLE
Broken zone export of SPF records

### ISSUE THREAD

**Issue by iBobik** [barnybug/cli53#138]
When I export zone with SPF record it will try to escape quotes:
```
@	300	IN	SPF	"\"v=spf1 include:_spf.google.com a ~all\""
```
This behavior brokes import by AWS GUI. When I remove `\"` at the beginning and end it will work.

**Comment by barnybug** [comment]
Please check out 0.6.7 release and let me know if this fixes.

**Comment by iBobik** [comment]
Seems OK, thank you.
