### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by iBobik** [barnybug/cli53#139]
How about to add this tool to Homebrew package manager (OS X)?

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook

**Comment by barnybug** [comment]
sure, fancy making the pull request for homebrew?

**Comment by iBobik** [comment]
I am not sure how packaging works there. Do you understand this guide?

Maybe there is some example of project with compiled binaries in Github releases:
https://github.com/Homebrew/homebrew/tree/master/Library/Formula

**Comment by barnybug** [comment]
Not on a mac, so not really able to progress this myself, I'm afraid.

**Comment by barnybug** [comment]
Closing

**Comment by blackjid** [comment]
I uploaded a homebrew formula. https://github.com/Homebrew/homebrew-core/pull/656

**Comment by barnybug** [comment]
Nice one!

**Comment by blackjid** [comment]
The formula was merged :)
