### ISSUE TITLE
Consistent ordering in zone file export?

### ISSUE THREAD

**Issue by boldandbusted** [barnybug/cli53#140]
Howdy. Love this tool. Works just great, especially for those of us who are not machines and don't like parsing JSON. I use it to version our AWS Route 53 zones by keeping a git repo up-to-date with our several zone files with a simple bash script.

I just noticed that records don't return in the same order on export. Is there an option I'm missing, or could this be a feature request? :) Why would this be useful? It would make diffing trivially easy to read.

Happy New Year! And thanks again for this swell tool.

**Comment by barnybug** [comment]
what version of cli53?

**Comment by barnybug** [comment]
Closing.
