### ISSUE TITLE
cli53 --version output !?!?!?

### ISSUE THREAD

**Issue by emayssat-ms** [barnybug/cli53#141]
$ cli53 -v
cli53 version

on ubuntu 14.04
cli53 compiled from source yesterday.

Emmanuel

**Comment by barnybug** [comment]
Expected - master builds are not versioned.

**Comment by emayssat-ms** [comment]
how can I get a version of the software with the download method today?
As far as I know, the older version(s) were removed from pypi.
Given that your software is not backward compatible (I don't blame you!), I need to have a version to make sure that the syntax I am using is the correct one.

I need to have a version returned (even if just the git sha!) to use this tool for production deployment.
how can I do that today?
If not possible, your code may have to be changed to return a version.

Regards,
--
Emmanuel

**Comment by barnybug** [comment]
Not certain what you refer to as "download method today"?
The downloadable binary builds are versioned:
% ./cli53-linux-amd64 --version
cli53 version 0.6.7

**Comment by emayssat-ms** [comment]
Ok, got it! Thanks.
I will download the binary version.
