### ISSUE TITLE
rrlist command is missing

### ISSUE THREAD

**Issue by mrunkel-ut** [barnybug/cli53#143]
The python version had an rrlist command that I found very useful for quickly looking up or searching for a record.

Don't know if you were planning on including it, but count this as my vote for yes. :)

Thanks for the great tool

**Comment by barnybug** [comment]
Hey - it produced almost exactly the same output as 'cli53 export', so I figured no point in keeping it. But feel free to argue your case :-)

**Comment by mrunkel-ut** [comment]
Ok. I can use the output from export.  I'll just need to modify some of my scripts.

FWIW, that's something to consider going forward, instead of removing what appears to be a redundant option, just leave it in place but have it do the same thing.  Stability is a good thing. :)

**Comment by mrunkel-ut** [comment]
But thank you for this tool... It's really appreciated.
