### ISSUE TITLE
rrcreate is missing the -x option

### ISSUE THREAD

**Issue by mrunkel-ut** [barnybug/cli53#144]
There doesn't seem to be a way to create a different TTL when creating records

**Comment by barnybug** [comment]
see: https://github.com/barnybug/cli53/#getting-started
or: https://github.com/barnybug/cli53/issues/137
or: https://github.com/barnybug/cli53/issues/142
:-)

**Comment by mrunkel-ut** [comment]
Oops. Sorry. :)
