### ISSUE TITLE
dns: not a TTL

### ISSUE THREAD

**Issue by EntryC0der** [barnybug/cli53#147]
Hello,

I'm running the Windows version of cli53, version 0.6.8

I'm running an export of my zone via the following command (note, the outcome is the same if I use the -f option): cli53.exe export testdomain.com > testdomain.com.txt

Once I do this, I have a text file formatted as shown:

$ORIGIN testdomain.com.
@	900	IN	SOA	ns-1336.awsdns-39.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
@	172800	IN	NS	ns-1336.awsdns-39.org.
@	172800	IN	NS	ns-76.awsdns-09.com.
@	172800	IN	NS	ns-603.awsdns-11.net.
@	172800	IN	NS	ns-1938.awsdns-50.co.uk.
test1	60	IN	A	10.10.10.100

I then try to reimport the file, making no changes (doesn't make a difference if I do make changes), using the following, and get the error below - also, --wait and --replace don't impact the outcome:

cli53.exe import testdomain.com --file c:\aws\zones\testdomain.com.txt --wait --replace
Error: c:\aws\zones\testdomain.com.txt: dns: not a TTL: "\x00t\x00e\x00s\x00t\x00d\x00o\x00m\x00a\x00i\x00n\x00.\x00c\x00o\x00m\x00.\x00\x00" at line:
 1:50

If I try to run the import using a BIND-generated file, it succeeds with no issue.  I'm not sure if I'm doing something incorrectly, or if there is a bug.

Thanks.

**Comment by barnybug** [comment]
It looks like a problem with the file encoding in the txt file from the shell redirection. This doesn't happen on linux/mac versions so I'm guessing it's something curious Windows itself is doing.

**Comment by EntryC0der** [comment]
Odd.  For some reason my export was generating as Unicode.  I was able to change my output to ASCII.  Thanks!
