### ISSUE TITLE
TrafficPolicy records support

### ISSUE THREAD

**Issue by r4um** [barnybug/cli53#148]
Right now existence of traffic policy records in a zone causes a panic. 

Doesn't seem a straight forward way to integrate with existing type of records, since these are 
handled [completely different](http://docs.aws.amazon.com/Route53/latest/APIReference/api-create-traffic-policy-instance.html) and are not created via the [ChangeResourceRecordSets](http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html)

While fetching the record
```
{
  Name: "zzz.foobar.com.",
  ResourceRecords: [{
      Value: "This resource record set includes an attribute that is unsupported on this Route 53 endpoint. Please consider using a newer endpoint or a tool that does so."
    }],
  TrafficPolicyInstanceId: "6906ceb8-3f15-4256-acca-70d50690acd2",
  Type: "CNAME"
}
```

I was planning a PR on the following lines.

1. While converting to bind fetch and store traffic policy instance details from the `TrafficPolicyInstanceId`, for example the following response
 
   ```
  {
  TrafficPolicyInstance: {
    HostedZoneId: "Z3HI02S8QFEO01",
    Id: "6906ceb8-3f15-4256-acca-70d50690acd2",
    Name: "zzz.foobar.com.",
    State: "Applied",
    TTL: 30,
    TrafficPolicyId: "884c7aa9-dd1f-4165-bae3-53d096eb9ac0",
    TrafficPolicyType: "CNAME",
    TrafficPolicyVersion: 1
  }
 }
  ```

 Would be a new type of AWS RR (`TFPL`?) translating to bind format as below
 
  ```
 zzz     30   AWS     TFPL    CNAME Z3HI02S8QFEO01 884c7aa9-dd1f-4165-bae3-53d096eb9ac0 1
 ```

2. While converting from bind to AWS, these records will be filtered from the usual RR's and separate TrafficPolicy   API calls need to be made.

Thoughts?

**Comment by barnybug** [comment]
Hi, thanks for looking into detail on this one.

It occurs to me supporting export (at least not panicing!) would be fairly trivial - update aws-sdk-go, and export the rrset with the value of TrafficPolicyId in the extra comment data (similar to how non-alias weighted/geo/latency records are handled).

This wouldn't help much for import, without the instance details as you suggest. This is where I'm a bit stuck - what's the purpose of attempting to support import of these? Perhaps to provide a means to backup zones? But how would it be any use backing up the associated policy instance without the policy+document too, and recreating that all on import if necessary.

I'm wondering whether shoe-horning this all into bind format is stretching it possibly further than intended!

Interested in your thoughts.

**Comment by r4um** [comment]
> This wouldn't help much for import, without the instance details as you suggest. This is where I'm a bit stuck - what's the purpose of attempting to support import of these? Perhaps to provide a means to backup zones? But how would it be any use backing up the associated policy instance without the policy+document too, and recreating that all on import if necessary.

Only thing this will help with is restoration of the record from a backup assuming the traffic policy isn't deleted.

Agreed without doing a full backup of metadata (Traffic policy itself, health checks etc.) this isn't fully useful. That being said, do you have plans to include these or see this tool doing it in future while creating exports for backup purpose (not necessarily in bind format) ?

> I'm wondering whether shoe-horning this all into bind format is stretching it possibly further than intended!

In general yes :), but for the export to be useful in any form these details (`ZoneId`, `TrafficPolicyId `, `TrafficPolicyVersion`) need to be included as `TrafficPolicyInstanceId` is generated when you create a record and is lost if you delete it.

How about supporting export with `TrafficPolicyInstance` details and while importing a zone warn 
the user we won't attempt to create these records (yet) ? or just warn user and skip these records during
export (breaks usefulness as at least a backup of some sort) ?

**Comment by barnybug** [comment]
> Agreed without doing a full backup of metadata (Traffic policy itself, health checks etc.) this isn't fully useful. That being said, do you have plans to include these or see this tool doing it in future while creating exports for backup purpose (not necessarily in bind format) ?

I've seen export used by a few as a backup policy (which was at least unanticipated for me, original intentions behind cli53 were just for one way import). But to be useful for managing of traffic policies cli53 would also need tpcreate (?), tpdelete, too.

So I guess it's more a question of what are users expecting cli53 to do (and also what I get as PR requests!).

How manageable do you think traffic policies would be just from the command line? I've not had the change to play with the UI yet / json format.

> How about supporting export with TrafficPolicyInstance details and while importing a zone warn 
> the user we won't attempt to create these records (yet) ? or just warn user and skip these records during
> export (breaks usefulness as at least a backup of some sort) ?

My preference would probably be for the latter. I'm not entirely comfortable with inventing a new sort of rdtype or having to hit another API to resolve these correctly. I could see the code getting pretty ugly quickly.

I think down the line a richer export format would be the way to handle this. Perhaps (ubiquitous) json.

**Comment by r4um** [comment]
> How manageable do you think traffic policies would be just from the command line? I've not had the chance to play with the UI yet / json format.

Building the policy from scratch will be too complicated, backup/restoration is still manageable. 

>My preference would probably be for the latter. I'm not entirely comfortable with inventing a new sort of rdtype or having to hit another API to resolve these correctly. I could see the code getting pretty ugly quickly.

True. Raised #152 for now.

> I think down the line a richer export format would be the way to handle this. Perhaps (ubiquitous) json.

Agreed, this would be the right way.

**Comment by barnybug** [comment]
Done
