### ISSUE TITLE
Sporadic failure

### ISSUE THREAD

**Issue by lso-rf** [barnybug/cli53#149]
I am running cli53 0.6.8 (aws-sdk-go v0.9.13), and running into
the following error only upon bootup of an instance:

   Error: UserHomeNotFound: user home directory not found.

which also returns a return code of 1, on the initial invocation of
the 'cli53 rrcreate'.  The 'cli53' command is of the form:

   cli53 rrcreate --debug --profile ${Profile} --wait --replace ${DomainName} "${HostName} ${TTL} CNAME ${PublicHostName}."

However, after instance is up, issuing the same command works as
expected(?!).  Here is an edited version of the IAM policy:

   {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Action": [
                  "route53:ChangeResourceRecordSets",
                  "route53:GetHostedZone",
                  "route53:ListResourceRecordSets"
              ],
              "Resource": "arn:aws:route53:::hostedzone/XXXXXXXXXXXXXX"
          },
          {
              "Effect": "Allow",
              "Action": "route53:GetChange",
              "Resource": "arn:aws:route53:::change/*"
          },
          {
              "Effect": "Allow",
              "Action": [
                  "ec2:DescribeTags",
                  "elasticloadbalancing:DescribeLoadBalancers",
                  "route53:ListHostedZones"
              ],
              "Resource": "*"
          }
      ]
   }

From looking at the code, it appears that the problem may be in the
SDK, but I'm not sure about it.

Thanks in advance for your assistance.

**Comment by barnybug** [comment]
Where are you running cli53 from upon bootup? Perhaps HOME isn't defined in this environment?

**Comment by lso-rf** [comment]
Hello Barnaby:
    OK, yes you are correct.  I wasn't thinking about the 'aws' requirement
for where it
would find the configuration directory from $HOME.  Defining the
environmental $HOME
fixed the problem.

Thanks for your help!

**Comment by barnybug** [comment]
ok, closing.
