### ISSUE TITLE
Wildcard delete of record fails with no records matched

### ISSUE THREAD

**Issue by davidwalter0** [barnybug/cli53#150]
cli53 rrcreate example.com '*.api2.test 3600 A 192.168.0.44'

cli53 rrdelete example.com '*.api2.test' A
Warning: no records matched - nothing deleted

**Comment by davidwalter0** [comment]
I tried your suggestion for the unit test, but had issues with installing the test tooling to verify them. Found another case and committed them to the fork.

**Comment by barnybug** [comment]
no worries - have fixed and tested
