### ISSUE TITLE
Just hangs

### ISSUE THREAD

**Issue by linuxgurugamer** [barnybug/cli53#153]
### cli53 version (cli53 --version)
cli53 version 0.6.9

### OS / Platform
CentOS 5 

### Expected behaviour
show list of zones or just return

### Actual behaviour
Just hangs

### Steps to reproduce
cli53 list

Please include full commands and/or bind files that demonstrate the issue, along with the output.
This command works, and shows that the credentials are correct:
aws route53 list-hosted-zones

cli53 just hangs when I do this:
cli53 list

### Have you or would you willing to contribute a fix? (potentially with assistance)
would be willing to test, but don't know go, no time to learn

**Comment by barnybug** [comment]
How are you providing credentials to cli53?

**Comment by linuxgurugamer** [comment]
In a credentials file:
~/.aws/config:
[default]
aws_access_key_id=*******
aws_secret_access_key=*******
region=us-east-1
output=json

~/aws/credentials:
[default]
aws_access_key_id=*******
aws_secret_access_key=*******

**Comment by barnybug** [comment]
"~/aws/credentials" - typo? Should be "~/.aws/credentials"
~/.aws/config isn't something read by cli53 - ~/.aws/credentials should work (just verified on latest release).

Failing that have you tried setting the environment variables?

**Comment by linuxgurugamer** [comment]
typo, it is ~/.aws/credentials
No, I haven't tried the env. vars, I'll try later today

**Comment by barnybug** [comment]
Any updates?

**Comment by linuxgurugamer** [comment]
no, and there won't be for a week or more, having surgery

**Comment by barnybug** [comment]
ok, closing ticket for now - please reopen when you have more info.
