### ISSUE TITLE
Adding MX Records Error

### ISSUE THREAD

**Issue by ahamilton9** [barnybug/cli53#154]
### cli53 version (cli53 --version)

0.6.9 (tried 0.6.8 first)

### OS / Platform

Linux x64 (Mint 17.3)

### Expected behaviour

Allow me to wrap my MX record rules in quotes to specify multiple. 

### Actual behaviour

Having a single record entry on the line works fine, but it errors the moment I wrap it in quotes, so I can't specify multiple. I'm following the syntax from the README as far as I can tell. It almost looks like it's parsing the quote as part of the row to add. 

### Steps to reproduce

```sh
# Working
~ ❯❯❯ cli53 rrcreate "testingdomain.com" '@ 300 MX 10 ASPMX.L.GOOGLE.COM.' --replace                                                                                                                                                                         ⏎ master
Created record: 'testingdomain.com. 300 IN MX 10 ASPMX.L.GOOGLE.COM.'

# Fails with quotes
~ ❯❯❯ cli53 rrcreate "testingdomain.com" '@ 300 MX "10 ASPMX.L.GOOGLE.COM."' --replace                                                                                                                                                                         master
Error: dns: bad MX Pref: "\"" at line: 2:10
```

### Have you or would you willing to contribute a fix? (potentially with assistance)
Relatively new to Python, but I could make an attempt if anyone can give me some direction.

**Comment by barnybug** [comment]
Hi, thanks for spotting this. The docs are incorrect (I think this was a mistake from translating from the previous version here). You can't currently create multiple records using rrcreate from the command, you would have to create a zone file and import it.

**Comment by barnybug** [comment]
The latest release 0.7.0, now supports this: (check out the README examples)
https://github.com/barnybug/cli53/releases/tag/0.7.0

**Comment by ahamilton9** [comment]
I updated to 0.7.0, and now I get this:

```sh
>>> cli53 -v
cli53 version
```

and running this command just gives me the help output:

```sh
>>> cli53 rrcreate "testingdomain.com" '@ 300 MX 10 ASPMX.L.GOOGLE.COM.' '@ 300 MX 20 ALT1.ASPMX.L.GOOGLE.COM.' '@ 300 MX 20 ALT2.ASPMX.L.GOOGLE.COM.' '@ 300 MX 30 ASPMX2.GOOGLEMAIL.COM.' '@ 300 MX 30 ASPMX3.GOOGLEMAIL.COM.'
NAME:
   cli53 rrcreate - create a record...
```

Also tried without the TTL, same thing. Also tried running them one at a time, but even if I only put --replace on the first command, it just tells me it already exists for the rest and fails out. 

I'll keep looking to make sure I'm not just missing something...

**Comment by barnybug** [comment]
Are you sure you're using 0.7.0 from the releases or your own build?

**Comment by ahamilton9** [comment]
Just rebuilt using the Go compiler method and I have the same weird "version is version" issue. Was trying the Linux x64 pre-built before. Checked a fresh terminal and no change.

**Comment by barnybug** [comment]
Does 0.7.0 release correctly report version for you?

**Comment by ahamilton9** [comment]
It does. Not sure why my compiled version failed, since I believe I was running the compiled version for the last update without issue.

**Comment by barnybug** [comment]
Sorry, you've lost me a bit - does either of 0.7.0 or source build work for you or both reporting the usage help?

**Comment by ahamilton9** [comment]
My apologies. The 0.7.0 pre-compiled release works just fine after I got rid of any version I had compiled from source. I'm no Go developer, so I'm assuming something in my go-lang files is wrong for compiling, but it's not an issue any longer now that I've got the release functional. Thanks!

**Comment by barnybug** [comment]
cool, ok!
