### ISSUE TITLE
How to set TTL?

### ISSUE THREAD

**Issue by jdavidbakr** [barnybug/cli53#155]
### cli53 version (cli53 --version)
cli53 version 0.6.9

### OS / Platform
AWS linux ami

I downloaded today the latest cli53 and am I mistaken that the TTL option is gone?  I have a script running on server boot that sets its CNAME, but the default TTL value of 3600 is not going to work.  In a previous version there was a --ttl option where I could set this in rrcreate, but I can't figure out how to set it in the current version.

**Comment by barnybug** [comment]
see: https://github.com/barnybug/cli53/#getting-started
or: #137
or: #142
or: #144
