### ISSUE TITLE
Assigning Multiple IPs for A record using Simple Routing

### ISSUE THREAD

**Issue by dkirkpatrick7** [barnybug/cli53#156]
cli53 version 0.6.9
NAME="Amazon Linux AMI"
VERSION="2015.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.09"
PRETTY_NAME="Amazon Linux AMI 2015.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

Using `cli53 rrcreate --replace zone record(s)` used to replace an A record in the specified Zone, setting up Simple routing on multiple IP addresses, as well as return the Route53 request ID. Now, it fails on multiple IPs in the records string.

```
$ cli53 rrcreate --replace XXXXXXXXXXXXXX "testing.service.region.classifier A XXX.XXX.XXX.XXX YYY.YYY.YYY.YYY ZZZ.ZZZ.ZZZ.ZZZ"
Error: dns: garbage after rdata: "YYY.YYY.YYY.YYY" at line: 2:69
```

With a single IP, the command works--

```
$ cli53 rrcreate --replace XXXXXXXXXXXXXX "testing.service.region.classifier A XXX.XXX.XXX.XXX"
Created record: 'testing.service.region.classifier.env.company.net. 3600 IN A XXX.XXX.XXX.XXX'
```

Looking cursorily at the zscan_rr.go (line 26) and zscan.go (line 939) files, it appears that it should be able to support multiple IPs. The check on zscan.go (line 946) appears to be the culprit; is there a syntax that I am missing in my command call.

Incidentally, I also noticed that the command does not return a request ID from AWS anymore as well. I am guessing that the rrcreate --wait option is the new solution going forward here, so I no longer need to use my request ID polling function. Looking at the debugging output, it appears that this change may have been done due to a change in the Route53 API output, but I digress.

Further, I see the weighted record example, but I really don't need a weighted solution, as this has a simple round-robin requirement. I am not a Go developer, but I would be willing to assist troubleshooting and learn, if this is deemed an actual bug.

Please advise. Thanks.

**Comment by barnybug** [comment]
Hi, to create round robin A records you need to specify the same record multiple times in a bind file, and import that, eg: file.txt
record A 127.0.0.1
record A 127.0.0.2

cli53 import domain --file file.txt

Afraid there's not a way of creating this from the command line directly.

**Comment by barnybug** [comment]
The latest release 0.7.0, now supports this: (check out the README examples)
https://github.com/barnybug/cli53/releases/tag/0.7.0
