### ISSUE TITLE
Allow creating multiple records using rrcreate

### ISSUE THREAD

**Issue by barnybug** [barnybug/cli53#157]
cli53 should allow multiple records to be specified as extra arguments to rrcreate. eg
cli53 rrcreate domain 'test A 127.0.0.1' 'test A 127.0.0.2'

Related to #156 and #154.

**Comment by barnybug** [comment]
Done https://github.com/barnybug/cli53/commit/b4113d2e2870067bff06ade2d35d63b8a128fb14

**Comment by dkirkpatrick7** [comment]
Cool! Thanks.
