### ISSUE TITLE
Issues calling cli53 from bash script to create A record

### ISSUE THREAD

**Issue by balvey** [barnybug/cli53#158]
### cli53 version (cli53 --version)
cli53 version 0.6.9

### OS / Platform
amazon linux

### Expected behaviour
create or update an A record with instance id and local ip address of ec2

### Actual behaviour
Error: dns: not a TTL: "${TTL}" 

### Steps to reproduce

#!/bin/bash
export ZONE="awstest.my.net"
export TTL="60"
export INSTANCE_ID=$(ec2-metadata | grep 'instance-id:' | cut -d ' ' -f 2)
export LOCAL_HOSTNAME=$(ec2-metadata | grep 'local-hostname:' | cut -d ' ' -f 2)
export LOCAL_IP=$(ec2-metadata | grep 'local-ipv4:' | cut -d ' ' -f 2)
cli53 rrcreate --replace ${ZONE} '${INSTANCE_ID} ${TTL} A ${LOCAL_IP}'

### Was the documentation missing information you required?

Please ensure you've checked: https://github.com/barnybug/cli53/blob/master/README.md

### Could you contribute a fix or help testing with this issue?

I believe this is just a matter of me not escaping quotes correctly but each attempt I've made at doing so has resulted in similar errors or just a dumping of the help instructions.

**Comment by balvey** [comment]
I've gotten it to work, sorry to bug you. 
I had to build the record into a variable and then call the variable as a single string with no single quotes. I added/modified the below two lines to my script to fix my script. 

export RECRD="${INSTANCE_ID} ${TTL} A ${LOCAL_IP}"

/usr/bin/cli53 rrcreate -d --replace $ZONE "$RECRD"

**Comment by barnybug** [comment]
Yes - in the shell single quote doesn't perform interpolation (ie putting in variables), whereas double quotes would have worked for you. Glad you found the answer!
