### ISSUE TITLE
Repository is missing .gitmodules file

### ISSUE THREAD

**Issue by AGWA** [barnybug/cli53#161]
When I try to install from source under Go 1.5.1 per the README, `go get -u github.com/barnybug/cli53` results in the following error:

```
# cd /path/to/gopath/src/github.com/barnybug/cli53; git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'vendor/github.com/davecgh/go-spew'
package github.com/barnybug/cli53: exit status 1
```

https://github.com/golang/go/issues/12573 suggested that this might be fixed in Go 1.6, however, I receive the exact same error under Go 1.6, so perhaps it's a problem with how the  repository is set up?

Thanks for any suggestions you may have.

`go version` output: `go version go1.6 linux/amd64`

**Comment by AGWA** [comment]
It appears that this repository uses sub-modules:

```
$ git ls-tree -r HEAD | awk '$2 == "commit"'
160000 commit 2df174808ee097f90d259e432cc04442cf60be21  vendor/github.com/davecgh/go-spew
160000 commit 193d1ecb466bf97aae8b454a5cfc192941c64809  vendor/github.com/go-ini/ini
160000 commit 0b12d6b521d83fc7f755e7cfc1b1fbdd35a01a74  vendor/github.com/jmespath/go-jmespath
160000 commit d8ed2627bdf02c080bf22230dbb337003b7aba2d  vendor/github.com/pmezard/go-difflib
160000 commit cbeaeb16a013161a98496fad62933b1d21786672  vendor/github.com/stretchr/objx
160000 commit 1f22c0103821b9390939b6776727195525381532  vendor/golang.org/x/crypto
160000 commit 7f88271ea9913b72aca44fa7fc8af919eacc17ce  vendor/golang.org/x/net
160000 commit 3cf1a407a4e2eedab950cb2caa897cb185354d0f  vendor/golang.org/x/text
160000 commit 344080534465c5613c3563c30fd38c031073841d  vendor/golang.org/x/tools
```

However, there is no `.gitmodules` file present in the repository so it's impossible for anyone to actually retrieve these sub-modules.  Please add a `.gitmodules` file to the repository.

**Comment by barnybug** [comment]
That's odd - it doesn't need/use submodules. What's odd is the travis build has worked happily without, but those links are stale so I've removed.

Please retry with latest master and let me know how that goes.

**Comment by barnybug** [comment]
Ah, thinking about it I guess 'go get -u' was explicitly doing the submodule init so only just picked up those stale modules. So hopefully it'll work now for you?

**Comment by AGWA** [comment]
That did it!  Thanks for the quick fix. Looking forward to using cli53 :smile:
