### ISSUE TITLE
Are sublocations supported?

### ISSUE THREAD

**Issue by bensie** [barnybug/cli53#162]
### cli53 version (cli53 --version)

0.7.1

### Could you contribute a fix or help testing with this issue?

Definitely I can help test, I might be able to help fix.

### Question

Hey @barnybug! Wondering if sublocations are supported:
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values-geo.html#rrsets-values-geo-location

Looks like current documentation really doesn't cover geolocation entries at all, but I was able to dig through the tests to figure some of it out. From what I can tell, sublocations are not supported at this time. On your radar to add or should I look into implementing it? Thanks for the great tool!

**Comment by barnybug** [comment]
Hi,

You should be able to import bind files using the AWS routing syntax you found in tests/geo.txt with 'subdivisionCode', eg:
geo	300	IN	A	127.0.0.2 ; AWS routing="GEOLOCATION" subdivisionCode=..

I say should - unverified, so let me know how you get on!
(and yes, the docs are lacking in this area - pull requests for these appreciated too!)

**Comment by bensie** [comment]
@barnybug Thanks, added to CLI in #163. I was unable to get the tests running, but the new code works for me :) Would you mind running the tests and taking a peek at the PR?
