### ISSUE TITLE
--replace fails windows builds

### ISSUE THREAD

**Issue by skenigma** [barnybug/cli53#166]
### cli53 version (cli53 --version) 
0.7.2

### OS / Platform 
Windows 10 64 Bit

### Expected behaviour
Replace or update entry

### Actual behaviour
Error "Error: InvalidChangeBatch: Tried to create resource record set [name='***HOSTNAME***', type='A'] but it already exists"

### Steps to reproduce
ran command: `cli53-windows-amd64.exe rrcreate --replace itron-hosting.com "***HOSTNAME*** 3600 A ***IPADDRESS***"`

Please include full commands and/or bind files that demonstrate the issue, along with the output.

### Was the documentation missing information you required?
No

Please ensure you've checked: https://github.com/barnybug/cli53/blob/master/README.md

### Could you contribute a fix or help testing with this issue?
I can test, yes

**Comment by barnybug** [comment]
Sorry, but I couldn't reproduce this in the latest release. The command you've given alone isn't enough to reproduce the issue - there must be something about the existing records you have.
Please re-open this issue if it still occurs, including full commands and/or bind files that demonstrate the issue.
