### ISSUE TITLE
Upper case in DNS entry fails ....

### ISSUE THREAD

**Issue by emayssat-ms** [barnybug/cli53#167]
# /usr/local/bin/cli53 rrcreate qabin.org 'zookeeper1.Druid003a.us-west-1 300 CNAME ec2-54-215-244-187.us-west-1.compute.amazonaws.com.' --replace --wait 
Error: InvalidChangeBatch: Tried to create resource record set [name='zookeeper1.druid003a.us-west-1.qabin.org.', type='CNAME'] but it already exists
	status code: 400, request id: c9816ed7-fd1d-11e5-acc5-9734f4e23360

# /usr/local/bin/cli53 rrcreate qabin.org 'zookeeper1.druid003a.us-west-1 300 CNAME ec2-54-215-244-187.us-west-1.compute.amazonaws.com.' --replace --wait 
Created record: 'zookeeper1.druid003a.us-west-1.qabin.org. 300 IN CNAME ec2-54-215-244-187.us-west-1.compute.amazonaws.com.'
Waiting for sync.........................
Completed

# cli53 --version
cli53 version 0.6.9
on ubuntu 14.04

Maybe you could automatically lowercase the DNS entries?

**Comment by barnybug** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible!

**Comment by barnybug** [comment]
Would you like to write a pull request for this? We'd be more than happy to walk you through the steps involved.
