### ISSUE TITLE
comments to broken godaddy zone export and perl fix

### ISSUE THREAD

**Issue by fsperling** [barnybug/cli53#171]
- MX records are also exported without trailing dots so they need to be fixed as well.

- I noticed that the perl fix also add trailing dots to records that have an @ as value. I'm not sure if that causes problems or not. The cause it the range [-a-zA-Z0-9.-_] more specifically .-_ is interpreted as the range of chars from 46 to 95. 

To fix both I'd suggest sth like:
`perl -pe 's/((CNAME|MX\s+\d+)\s+[-a-zA-Z0-9._]+)(?!.)$/$1./i'`

**Comment by barnybug** [comment]
Nice catch, updated. Thanks.
