### ISSUE TITLE
Trace/breakpoint trap

### ISSUE THREAD

**Issue by Kevin-McIsaac** [barnybug/cli53#172]
cli53 was running fine until a few weeks/month ago now it terminates with error message Trace/breakpoint trap. I downloaded and installed version 0.7.4, then some older versions, e.g., 0.6.9 and 0.6.1.

Since this is not specific to newer version, I'm gussing the breakpoint is in a library used by cli53. I'm using a standard AWS linux AMI. 

### cli53 version (cli53 --version)
0.7.4 and earlier

### OS / Platform
Linux  4.4.5-15.26.amzn1.x86_64 #1 SMP Wed Mar 16 17:15:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Actual behaviour
Trace/breakpoint trap

### Steps to reproduce
cli53 --version

**Comment by barnybug** [comment]
Sorry, I don't follow exactly what you mean by "Trace/breakpoint trap". Please could you include more detail on this.

Please re-open this issue with the information.

**Comment by Kevin-McIsaac** [comment]
When I run cli53 the program exits immediately with status 133 and the the text "Trace/breakpoint trap" printed on the screen. My console looks like this

    [ec2-user@ip-172-31-11-85 tmp]$ cli53 --version
    Trace/breakpoint trap
    [ec2-user@ip-172-31-11-85 tmp]$ 

I did some reading and according to [this](http://tldp.org/LDP/abs/html/exitcodes.html) exit status 133 is an exit due to signal 5. According to [this](http://www.ucs.cam.ac.uk/docs/course-notes/unix-courses/Building/files/signals.pdf), signal 5 is SIGTRAP, which which is used from within debuggers and program tracers. 

My limited understanding is that cli53, or some library it is calling, has a debugger breakpoint turned on and the code is hitting this and exiting. Given that this only started recently and that it affect older version of cli53, it seems that the problem might be in a library.

I reproduced this on a new AWS t2.micro instance running Amazon Linux AMI 2016.03.0 (HVM), SSD Volume Type - ami-f2210191.  This means anybody using and Amazon Linux AMI will experience this problem.

I installed gdb and ran the program and it stops at the breakpoint, however as the executable is stripped, the backtrace just print
    #0  0x080989ec in ?? ()
    #1  0xffffc3a0 in ?? ()
    #2  0x00000000 in ?? ()

**Comment by barnybug** [comment]
Thanks for the extra information. I must admit, this is very odd - I've never seen this error message before. Also had many successful reports of users on Amazon Linux, so I can't believe would explain the issue either.

For this system, you should be using 'cli53-linux-amd64'
Could I check, which executable are you using? (sha256sum cli53)

**Comment by Kevin-McIsaac** [comment]
You were correct, I had the wrong version of the executable.  I did not know that x86_64 meant it was amd64.

Sorry for wasting your time.
