### ISSUE TITLE
NS records are not deleted on import

### ISSUE THREAD

**Issue by fsperling** [barnybug/cli53#173]
Importing records where I deleted a NS record do not lead to changes/update of the zone.

$ cli53 export roomguru.ph.

$ORIGIN roomguru.ph.
@       900     IN      SOA     ns-831.awsdns-39.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
@       172800  IN      NS      ns-831.awsdns-39.net.
@       172800  IN      NS      ns-1176.awsdns-19.org.
@       172800  IN      NS      ns-1974.awsdns-54.co.uk.
@       172800  IN      NS      ns-44.awsdns-05.com.

$ cat roomguru.ph
$ORIGIN roomguru.ph.
@       900     IN      SOA     ns-831.awsdns-39.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
@       172800  IN      NS      ns-831.awsdns-39.net.
@       172800  IN      NS      ns-1974.awsdns-54.co.uk.
@       172800  IN      NS      ns-44.awsdns-05.com.

$ cli53 import --replace --wait --file roomguru.ph roomguru.ph
4 records imported (0 changes / 0 additions / 0 deletions)

$ cli53 export roomguru.ph.
$ORIGIN roomguru.ph.
@       900     IN      SOA     ns-831.awsdns-39.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
@       172800  IN      NS      ns-831.awsdns-39.net.
@       172800  IN      NS      ns-1176.awsdns-19.org.
@       172800  IN      NS      ns-1974.awsdns-54.co.uk.
@       172800  IN      NS      ns-44.awsdns-05.com.

**Comment by barnybug** [comment]
You need to use the `--auth` flag for this purpose.
