### ISSUE TITLE
Problem in replacing existing record in route53 using specific profile

### ISSUE THREAD

**Issue by murarisumit** [barnybug/cli53#175]
### Expected behaviour
`--replace` parameter in below query wasn't picking up the profile given

1. `cli53 rrcreate --replace domain.com 'sudmitt 60 A 1.2.3.8' --profile no-default-profile-name`

*BUT*

2. `cli53 rrcreate  domain.com 'sudmitt 60 A 1.2.3.8' --profile no-default-profile-name --replace `

was working.

So `replace` switch is used before `profile-name` switch wasn't picking the given aws-profile

*First query was picking default profile*

### Was the documentation missing information you required?
No

Please ensure you've checked: https://github.com/barnybug/cli53/blob/master/README.md

### Could you contribute a fix or help testing with this issue?
Sure, I'll will help, wherever I can.

**Comment by barnybug** [comment]
Hi, the command line library cli53 uses expects the parameters to be given together in the command line (either before or after the other 'plain' arguments).

Not much I can do so I'll close this issue, but if you're inclined you could open an issue directly with that project: https://github.com/codegangsta/cli/
