### ISSUE TITLE
PTR creation appending in-addr.arpa zone info to record values

### ISSUE THREAD

**Issue by dpalomin** [barnybug/cli53#180]
### cli53 version (cli53 --version)
cli53 version 0.7.4

### OS / Platform
CentOS 6

### Expected behaviour
I have two private hosted zones
{
  CallerReference: "sanitized",
  Config: {
    Comment: "private hosted zone",
    PrivateZone: true
  },
  Id: "/hostedzone/XXXXXXXXXXXX",
  Name: "subdomain.mydomain.net.",
  ResourceRecordSetCount: 3
}
{
  CallerReference: "sanitized",
  Config: {
    Comment: "private hosted zone for PTR records",
    PrivateZone: true
  },
  Id: "/hostedzone/YYYYYYYYYYYY",
  Name: "192.178.10.in-addr.arpa.",
  ResourceRecordSetCount: 3
}

I'm trying to create a PTR record like this:
cli53 rrcreate YYYYYYYYYYYY '178 60 PTR ip-10-178-192-178.subdomain.mydomain.net' --replace

I'm expecting record that looks like this from `dig -x 10.178.192.178`:
178.192.178.10.in-addr.arpa. 60 IN  PTR ip-10-178-192-178.subdomain.mydomain.net.

But instead I get this:
178.192.178.10.in-addr.arpa. 60	IN	PTR	ip-10-178-192-178.subdomain.mydomain.net.192.178.10.in-addr.arpa.

Am I misusing cli53, or is this a bug?  

### Was the documentation missing information you required?
I didn't see any PTR examples in there...

### Could you contribute a fix or help testing with this issue?
I should be able to help with testing.

**Comment by barnybug** [comment]
Zones need a trailing dot to qualify them, otherwise they are relative.

**Comment by dpalomin** [comment]
D'oh, thank you for the education!
