### ISSUE TITLE
Target r53 zone in another account

### ISSUE THREAD

**Issue by aaroncaito** [barnybug/cli53#182]
Would like to be able to use cli53 to update zones hosted in another account.

Ideally we'd be able to use an iam instance role + target account id via cli or configuration file to perform this.

**Comment by barnybug** [comment]
Hi, as I see you've found - this has been discussed before and requires sdk support:
https://github.com/barnybug/cli53/issues/135
The linked sdk ticket is tracking support for this. Closing this.
