### ISSUE TITLE
Zone replication?

### ISSUE THREAD

**Issue by aaroncaito** [barnybug/cli53#183]
Very helpful tool thanks for that.

Tried this
`cli53 import zone-a --profile a --file <(cli53 export zone-b --full --profile b)`
Doesn't work.

Skimming through code it looks like your export grabs everything as resource records to begin with, would be great if we could add a profile b to go with a zone b for a replication service.

If not at least allowing changing api from CREATE to UPSERT might still achieve the needful, particularly with the import functionality.

Usecase: sharing private hosted zone between two accounts, need frequent replication until route53 team adds account b vpc's to whitelist for account a route53 phz.

**Comment by barnybug** [comment]
Have you tried the `--replace` option on import?

**Comment by aaroncaito** [comment]
Sorry I'd not seen the --replace flag. I'll give that a shot.

-Aaron Caito

c. 317.965.6142 // aaron.caito@gmail.com

**Comment by barnybug** [comment]
Closing
