### ISSUE TITLE
Add -format flag to output JSON

### ISSUE THREAD

**Issue by kwilczynski** [barnybug/cli53#185]
I am not sure how much effort this is going to be, but it would be nice to have the ability to parse and process cli53's output. At the moment the output looks like JSON but it's not quite the correct format, thus an attempt to parse would fail, for example:

```bash
$ cli53 list | jq .
parse error: Invalid numeric literal at line 2, column 18
```

If you could consider either adding a JSON flag, or simply output JSON by default, that would be truly spot on, indeed.

I find cli53 extremely useful and fast (compared to awscli), thus I would be overjoyed if there would be an ability to pipe output to jq (or else) for some processing.

**Comment by barnybug** [comment]
good idea.

I'm not particularly keen on JSON being the default (not really human readable for the average human), but think this is a good idea still. And the existing output for list is ugly!

**Comment by kwilczynski** [comment]
@barnybug thank you so much! ❤️ 

It does not need to by JSON by default, but something like `--json`, or perhaps `--output` which would take `table`, `json`, `csv`, etc., would be splendid. Granted, adding like that would most likely require adding a concept of a formatter interface to each type handled at the moment so that they would add concrete implementation to decorate the output as needed.

**Comment by barnybug** [comment]
If anyone on this issue can give this a try and see from master (see: https://github.com/barnybug/cli53#building-from-source)
Feedback welcome.

**Comment by kwilczynski** [comment]
@barnybug this is absolutely amazing! Simply outstanding thing to have. Thank you so much!
