### ISSUE TITLE
Request: automatically synchronize PTR records when A/AAAA records are changed.

### ISSUE THREAD

**Issue by shadowbq** [barnybug/cli53#187]
### cli53 version (cli53 --version)

cli53 version 0.7.4

## Feature Request

Could we auto create a PTR for each A/AAA record pointed to a specific zone?

$ cli53 sync-zone 1.10.in-addr.arpa. example.com
$ cli53 rrcreate example.com 'www 60 A 192.168.0.1'

**Comment by barnybug** [comment]
I think this is something you could readily script - ie pipe cli53 export output through perl or similar, to make the ptr zone file, and then run cli53 import --replace to synchronise this. So as such I wouldn't consider this a built in feature.
