### ISSUE TITLE
Some CNAME records are missing periods

### ISSUE THREAD

**Issue by nativex-dlepinski** [barnybug/cli53#189]
### cli53 version (cli53 --version)
.0.7.4

### OS / Platform
Linux

### Expected behaviour
The code to fix CNAMEs records should add a period at the end of each CNAME record.

### Actual behaviour
The code is fixing some CNAME records, but doesn't seem to fix CNAME records with dashes (-) in the domain url.

### Steps to reproduce

We have multiple zones with dashes in the CNAME records. This issue happens in each one of them.

For example, this is a line from one of the bind files.
aws	60	IN	CNAME	url-with-dashes.domain.co ; AWS routing="WEIGHTED" weight=1 healthCheckId="healthcheckID" identifier="A1"

No period is being added at the end of the domain.co, but periods are being added at the end of CNAMES without dashes in the domain within the same bind file.

### Was the documentation missing information you required?

Please ensure you've checked: https://github.com/barnybug/cli53/blob/master/README.md

### Could you contribute a fix or help testing with this issue?
I will gladly help test.

**Comment by barnybug** [comment]
Possible you could suggest the change to the regex to fix this?

**Comment by danpritts** [comment]
I think I'm seeing the same issue, and the domain in question doesn't have any dashes in it.  

The domain is 5 ascii characters then .net.  Here's an edited transcript.  

```
~/.aws@staging% ./cli53-linux-amd64 export short.net
$ORIGIN short.net.
@      	900    	IN     	SOA    	ns-1341.awsdns-39.org. hostmaster.icpsr.umich.edu. 2013021200 7200 900 1209600 86400
@      	60     	IN     	A      	1.2.3.4 ; AWS routing="FAILOVER" failover="PRIMARY" healthCheckId="X" identifier="Primary"
@      	60     	IN     	A      	5.6.7.8 ; AWS routing="FAILOVER" failover="SECONDARY" healthCheckId="Y" identifier="Secondary"
@      	300    	IN     	MX     	10 some.host.
@      	172800 	IN     	NS     	ns-1341.awsdns-39.org.
@      	172800 	IN     	NS     	ns-1714.awsdns-22.co.uk.
@      	172800 	IN     	NS     	ns-553.awsdns-05.net.
@      	172800 	IN     	NS     	ns-478.awsdns-59.com.
www    	300    	IN     	CNAME  	short.net
```

I see the same results with "short.com" and "short.org".

Using your binary distribution of 0.7.4 on linux.  

I doubt this matters but I am on an old aws account without a default VPC.

I am not sure where the code with the regex is, i poked around for a bit and couldn't find it.  I'm half-decent with regexes though so i may be able to help if you point me in the right direction.

**Comment by danpritts** [comment]
after i changed the value of the www CNAME with cli53, the export command gave me the properly . terminated CNAME.  (Or @ when i set it to point to short.net).

i changed the value of the www CNAME in the aws web interface, setting it to 'short.net', with no trailing period.  That's probably how it was before I started.  dns queries from amazon show the properly . terminated name, but cli53 dumps the undotted name without correction.

**Comment by barnybug** [comment]
The conflict here is whether cli53 preserves the defined bind behaviour for relative/absolute names, or the rather looser route53 behaviour. They're not compatible with each other. route53 behaving this way is a bit ill-defined (would be better handled at the interface level if it's applying fixes for poor data), so I'm inclined to leave cli53 behaviour as is for now.

**Comment by danpritts** [comment]
Any chance you can watch for such names, and if they are terminated with a defined .tld, print a warning to standard error?

Of course, that leaves you having to manage the list of .tlds.   You could do that in the build process, I guess - this looks helpful:  https://gist.github.com/stantonk/b0a937ca9c035a83b14c

Even grabbing the list of 20 or 50 most popular tlds and checking for those would be a win. 

and while i'm here, thanks for cli53, regardless of this request.  Made my life easier.
