### ISSUE TITLE
Creating SRV records?

### ISSUE THREAD

**Issue by bobuehlein** [barnybug/cli53#190]
This is more of a "can we do it" than a bug.

Our company uses Office 365 for email and the like. Each record has a number of cnames a text record and a few SRV records. Is it possible to add a SRV record using cli53? 

Thanks for this great work. I'm scripting some of the common o365 settings... it will be much faster than the R53 console!

**Comment by barnybug** [comment]
Should be supported - give it a try and see!

**Comment by bobuehlein** [comment]
imports work, but what would the command like be?

cli53 rrcreate domain.com  SRV ????

**Comment by barnybug** [comment]
Format is the same as bind files - just put the part after in quotes. See README for comparable examples.

**Comment by bobuehlein** [comment]
That was perfect. After a little trial and error I have the svr records setup. So happy I found this :) my bash script saves be tons of work :)

**Comment by davidcsi** [comment]
@bobuehlein can you share how you did it?
I haven't been able to.

Thanks!

**Comment by bobuehlein** [comment]
Hey @davidcsi 

I still use this to this day! Setup a new domain just today. This does everything but the MX and TXT records since those change for each domain  for us and need to be entered by themselves

Just make it executable and  "sh yourfilename.sh domainname.com"

`
#!/bin/sh 

        cli53 create $1
        cli53 rrcreate $1 'autodiscover 3600 CNAME autodiscover.outlook.com.'
        cli53 rrcreate $1 'sip 3600 CNAME sipdir.online.lync.com.'
        cli53 rrcreate $1 'lyncdiscover 3600 CNAME webdir.online.lync.com.'
        cli53 rrcreate $1 'msoid 3600 CNAME clientconfig.microsoftonline-p.net.'
        cli53 rrcreate $1 'enterpriseregistration 3600 CNAME enterpriseregistration.windows.net.'
        cli53 rrcreate $1 'enterpriseenrollment 3600 CNAME enterpriseenrollment.manage.microsoft.com.'
        cli53 rrcreate $1 '_sip._tls 3600 SRV 100 1 443 sipdir.online.lync.com.'
        cli53 rrcreate $1 '_sipfederationtls._tcp 3600 SRV 100 1 5061 sipfed.online.lync.com.'
`

**Comment by bobuehlein** [comment]
[o365.txt](https://github.com/barnybug/cli53/files/3237637/o365.txt)

See if this displays better :) Save as a .sh and make executable.

**Comment by davidcsi** [comment]
nice! thanks!
