### ISSUE TITLE
Could you provide example with healthcheck?

### ISSUE THREAD

**Issue by emayssat-ms** [barnybug/cli53#191]
I understand the health checks are created externally.
I would like to create a master record that can point to 2 weighted records and if there is a heath issue, then all get redirected to the healthy one.

It is not clear to me how to do that with cli53.
Could you provide a similar/simple example on how to use health checks? 

Thanks,

**Comment by barnybug** [comment]
see: https://github.com/barnybug/cli53/blob/master/internal/features/commands.feature
