### ISSUE TITLE
Zone import cannot add alias for both IPv4 and IPv6

### ISSUE THREAD

**Issue by milgner** [barnybug/cli53#195]
### cli53 version (cli53 --version)
0.8.2

### OS / Platform
`Linux milgner 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux`

### Expected behaviour
Import a file with two aliases that target different record types (`A` and `AAAA`), creates two alias records in the zone. It is possible to create two records in the web interface, so the import should probably do the same.

```
@ 3600 AWS ALIAS A distribution_id.cloudfront.net. hosted_zone_id NO
@ 3600 AWS ALIAS AAAA distribution_id.cloudfront.net. hosted_zone_id NO
```

### Actual behaviour
The second record specification overrides the first, creating only one record (shown as `AAAA ALIAS ...` in the web interface).

### Steps to reproduce
Run `cli53 import` with a zone file with two aliases, as shown above.

### Could you contribute a fix or help testing with this issue?
I will gladly try implementing a fix but probably won't find any time in the next 10 days and my Go-fu is still in its early stages ;) Let me know if I can assist with testing or debugging though.

**Comment by barnybug** [comment]
Fixed, will be in the 0.8.3 I'm just doing.
