### ISSUE TITLE
Listing zones never returns results (>100 zones)

### ISSUE THREAD

**Issue by floppym** [barnybug/cli53#196]
### cli53 version (cli53 --version)
0.8.2
0.8.3

### OS / Platform
Linux

### Expected behaviour
List of hosted zones is returned.

### Actual behaviour
Nothing happens; the program just hangs.

### Steps to reproduce
`cli53 list`

I think it might be running into a rate limit on AWS when paginating more than 100 hosted zones.

**Comment by barnybug** [comment]
Mind trying master (08548439f2d8229df99cad4cfe0b666165c67cb8)?
thanks

**Comment by floppym** [comment]
`go get` seems to be broken atm.

```
floppym@naomi cli53 % export GOPATH=$PWD
floppym@naomi cli53 % go get github.com/barnybug/cli53
# cd /home/floppym/tmp/cli53/src/github.com/barnybug/cli53; git submodule update --init --recursi
fatal: No url found for submodule path 'vendor/github.com/go-ini/ini' in .gitmodules
package github.com/barnybug/cli53: exit status 128
```

**Comment by floppym** [comment]
I was able to build despite the `go get` error, and the problem seems to have been resolved. Thanks!

**Comment by barnybug** [comment]
Great, thanks for testing. Not sure how many > 100 zone users we have, so thanks for spotting that.
Have fixed the go get issue too.
