### ISSUE TITLE
export is failing for a particular zone

### ISSUE THREAD

**Issue by BhanuCh** [barnybug/cli53#197]
### cli53 version (cli53 --version)

cli53 version 0.8.2

### OS / Platform

Linux  x86_64 x86_64 x86_64 GNU/Linux ( amazon Linux Ec2 instance)
### Expected behaviour
cli53 export <my zone id> --profile <profile name>
list the resource records in BIND format
### Actual behaviour
Error: Zone <my zone id> not found

### Steps to reproduce

cli53 export is not working for a particular zone. it says Error: <my zone > not found.

aws cli is working fine with that zone. 

 aws --output text --region us-west-2 route53 list-resource-record-sets --hosted-zone-id <my zone id> --profile <my profile>
is returning the resource records as expected.

The problem is with a particular zone.

**Comment by barnybug** [comment]
This issue has no reproducible steps.
Please re-open this issue, including full commands and/or bind files that demonstrate the issue.

**Comment by BhanuCh** [comment]
Working for an Enterprise and the domain information is sensitive. I  can't provide you the actual commands. I am iterating over 20000 hosted zones. I do have issue with only one zone.

**Comment by barnybug** [comment]
Wow, your Amazon bill must be huge! :-)

I'm not asking for specific details - appreciate these are sensitive, just reproduction steps. Use a test account, and see if you can recreate the conditions for this problem. Without them I don't have much to go upon, and so limited chance of fixing the issue.

Other questions that might help:
- has this worked in a previous version of cli53?
- could you try the previous version 0.8.1?
- does specifying that zone by the zone ID work?
- if you turn on debug (-d) `cli53 export -d`, are there obvious reasons?
- could you attach the debug logs, anonymised where necessary

**Comment by BhanuCh** [comment]
I am working with the newest version. 
I will try to install the old version and try to reproduce the issue. 
yes by specifying zone by name it works. but specifying by ID it doesn't work.

the -d flag to debug is not working.
cli53 export -d <domain name> --profile <profile name>

where as  
cli53 export <domain name> --profile <profile name>
works perfect..!

**Comment by barnybug** [comment]
ah, I see - so you are passing IDs to `cli53 export` not names? This wasn't clear from your original report.

@BhanuCh could you confirm @kfeldmann's fix solves the problem for you?

**Comment by BhanuCh** [comment]
The fix by @kfeldmann  solves the problem. As mentioned by @kfeldmann  the problem is with zone Id length check in the code. Thank you @kfeldmann .
