### ISSUE TITLE
How to remove a single IP from a round robin A record

### ISSUE THREAD

**Issue by andreasunterhuber** [barnybug/cli53#200]
### cli53 version (cli53 --version)
cli53 version 0.8.5

It's possible to remove a single IP from a round robin A record? 
speed.cdn.test.com.	300	IN	A	1.1.1.1
speed.cdn.test.com.	300	IN	A	2.2.2.2
speed.cdn.test.com.	300	IN	A	3.3.3.3
I want remove just the IP "2.2.2.2" from this collection. What would be the best approach?
Thanks a lot

**Comment by andreasunterhuber** [comment]
I've solved it this way: 

```
HOST_NAME="speed"
TTL="300"
CURRENT_IPS=($(cli53 export -f "cdn.test.com" | grep "speed.cdn.test.com" | awk '{print $5}'));
for i in "${CURRENT_IPS[@]}"; do if [ $i != $PUBLIC_IP ]; then echo $i && IPCMD+=("$HOST_NAME $TTL A $i"); fi done
/usr/local/bin/cli53 rrcreate --replace "cdn.test.com" "${IPCMD[@]}"
```

**Comment by barnybug** [comment]
Closing
