### ISSUE TITLE
TXT Record with pre-escaped backslashing get doubled

### ISSUE THREAD

**Issue by jnegro** [barnybug/cli53#205]
### cli53 version (cli53 --version)
current

### OS / Platform
Linux

### Expected behaviour
Importing a zone file into AWS Route53 should create identical TXT Records

### Actual behaviour
backslash escape characters in a quoted string of TXT Record are double escaped.  This is particularly happening with my DKIM records where semicolons need to be escaped by almost every provider including Dyn.

### Steps to reproduce
1) Get a zone file with a TXT DKIM record that includes escaped semicolons
2) Import to R53
3) View the record and see the extra slashes

Please include full commands and/or bind files that demonstrate the issue, along with the output.

### Was the documentation missing information you required?

Please ensure you've checked: https://github.com/barnybug/cli53/blob/master/README.md

### Could you contribute a fix or help testing with this issue?
I'm going to take a look at it now.  I believe I see the code involved, but I'm not versed in Go.  I'll let you know if I find anything

**Comment by jnegro** [comment]
Follow up - I believe the issue is in util.go starting at line 171.  I'd say we could either:

1)  Not run the replacer on TXT records
2) Somehow exclude \; during replacement, or put \\; back to \; afterwards
3) Something I haven't thought of.

**Comment by barnybug** [comment]
Good spot, fixed.
