### ISSUE TITLE
Instances?

### ISSUE THREAD

**Issue by peterhallen** [barnybug/cli53#208]
### cli53 version (cli53 --version)
8.6
### OS / Platform
OS X el capitan
### Expected behaviour
instances --match "Name:Value" <zoneid>  create records
### Actual behaviour
Getting DNS records
No instances found
0 records upserted
### Steps to reproduce
instances --match "Name:Value" <zoneid> 
Please include full commands and/or bind files that demonstrate the issue, along with the output.

### Was the documentation missing information you required?
Yes, Changelog says "instances" in BETA and 8.6 seems to not work
Please ensure you've checked: https://github.com/barnybug/cli53/blob/master/README.md

### Could you contribute a fix or help testing with this issue?
Sorry, operator only, but I will buy you beers if you're close to NYC 👍

**Comment by barnybug** [comment]
Check you're using the --match option correctly:
```
   --match value          regular expression to select which Name tags to use
```

**Comment by peterhallen** [comment]
Yep. That's exactly how I'm using it. 
Example:
cli53 instances --match <name of server> <zone ID> 

FYI instances is not working even when I leave out --match
My expectation is that if I leave off the --match flag it should get all the instance Names and create/upsert records as CNAMEs in route53. 

I have been a user of the python version for some years now. I wanted to upgrade to the Go version to receive any updates.

**Comment by barnybug** [comment]
Ah ok - you'd said "Name:Value" which confused me.

Are the instances in the same account and the region defined by $AWS_REGION?
Have you tried passing the region explicitly? (`--region`)
Are they in the running state?
Could you provide debug output (`instances -d`)?

Sorry - simple questions, but it works here, so without a reproduction case you'll have to do the investigative work on this one.

**Comment by barnybug** [comment]
Finally - how many instances are in the account and how many of these have Name tags?

**Comment by barnybug** [comment]
This commit may fix your issue:
https://github.com/barnybug/cli53/commit/59dbde12cb73415823fcf43d6c17bb52923f6582

I can't say for sure if you don't reply my comments, but please reopen this with the details if the problem still persists with the latest release.

**Comment by peterhallen** [comment]
@barnybug Sorry for the delay. I was away for the holiday. Hope you're well. 

It looks like specifying the `--region us-east-1` got me better results.

Seems as though private/internal zones with no public hostnames get up/inserted into the record set if the instance has a public record. 
i.e. `cli53 instances --region us-east-1 --match jenkins <zoneID>` will do an upsert because that instance has a public ec2 address - `ec2-1-2-3-4.compute-1.amazonaws.com`

Instances with no public address get just a `.` inserted. 

I have instances with internal naming a la `ip-172.16.0.100.ec2.internal` 

What I'd like is the ability to explicitly insert private ec2 names as a `CNAME` to `<name-of-instance.aws.domain.tld>`

Is that possible?
