### ISSUE TITLE
Why does rrcreate require to "ListHostedZonesByName"?

### ISSUE THREAD

**Issue by tknecht** [barnybug/cli53#210]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
0.8.7

### OS / Platform
4.4.0-57-generic #78-Ubuntu SMP
x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce
```
root@host:~# cli53 rrcreate --replace example.com '<hostname> 60 A <IP>'

Error: AccessDenied: User: arn:aws:iam::718XXXXXX454:user/<username> is not authorized to perform: route53:ListHostedZonesByName
	status code: 403, request id: 163bc938-d28c-11e6-93ad-XXXXXXXXXXXX
```

### Expected behaviour
There should not be a need to "ListHostedZonesByName" when using rrcreate.

"ListHostedZonesByName" requires "*" as Resource. This will break every time when the Resource is limited to one or more specific domains.

### Have you checked if the documentation has the information you require?
Yes.

### Could you contribute a fix or help testing with this issue?
Testing Yes.
Fixing No.

**Comment by barnybug** [comment]
To create the record cli53 needs to lookup zone name -> zone ID.
You can avoid this step by passing in the zone id (starting Z... - see cli53 list).

**Comment by barnybug** [comment]
Ping

**Comment by tknecht** [comment]
Okay got it. Thanks!
