### ISSUE TITLE
unable to create alias to elb

### ISSUE THREAD

**Issue by bobuehlein** [barnybug/cli53#213]
### Issue type

 - Bug report

### cli53 version (cli53 --version)
0.8.7
### OS / Platform
Mac 10.12
### Steps to reproduce

cli53 rrcreate domain.com 'myalias AWS ALIAS A dualstack.myname.us-east-1.elb.amazonaws.com. $self false' 

and 

cli53 rrcreate domain.com 'myalias AWS ALIAS A dualstack.myname.us-east-1.elb.amazonaws.com.  ABCDEFABCDE false' 

### Expected behaviour
Create the alias to the ELB.

### Actual behaviour
Error: InvalidChangeBatch: Tried to create an alias that targets dualstack.myname.us-east-1.elb.amazonaws.com., type A in zone ABCDEGABCDR, but the alias target name does not lie within the target zone
	status code: 400, request id: b61893fa-dd8d-11e6-84bc-2589eab727d5

### Have you checked if the documentation has the information you require?

yes

**Comment by barnybug** [comment]
You need to use the zone id the aws tools give you for ELB, see:
https://docs.aws.amazon.com/cli/latest/reference/elb/describe-load-balancers.html

**Comment by bobuehlein** [comment]
I was using the wrong ID... I was using the domain ID, and not the ELB Id. Thanks for setting me straight. Moving 300 domains to ELB, this will be most useful :)

**Comment by barnybug** [comment]
Fun! Glad I could help.
