### ISSUE TITLE
Make releases binary for alpine

### ISSUE THREAD

**Issue by vanaf** [barnybug/cli53#217]
### Issue type
Feature request
### cli53 version (cli53 --version)
0.8.7
### OS / Platform
Alpine / amd64
### Steps to reproduce
Current binary exits silently with exit code 127

### Expected behaviour

There should be alpine-linux binary that should work fine on alpine
Like on docker-gen project:
https://github.com/jwilder/docker-gen/releases

### Actual behaviour
Current binary exits silently with exit code 127

**Comment by barnybug** [comment]
There's a few Dockerfiles about to build this, eg: https://github.com/jeekajoo/alpine-cli53. I'd suggest using those instead of our binary releases.

**Comment by barnybug** [comment]
Ah, or I forgot about this: https://github.com/barnybug/cli53/commit/88cc14c55633a1e76cb494b88a35bb0bdd2ad51d
