### ISSUE TITLE
The current 0.8.7 release is not available for "pip install cli53"

### ISSUE THREAD

**Issue by nkadel-skyhook** [barnybug/cli53#219]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
Version 0.8.7

### OS / Platform
All

### Steps to reproduce
> pip install cli53
> cli53 --version
cli53 0.5 is no longer being actively maintained
( More debris ignored)

### Expected behaviour
Install and report the current 0.8.7 verion

### Actual behaviour

```
> pip install cli53
> cli53 --version
cli53 0.5 is no longer being actively maintained
```

### Could you contribute a fix or help testing with this issue?
Afraid not, I've not been putting modules into pypi. I assume the author has, because version 0.5.0 is still published for pypi.org.

**Comment by barnybug** [comment]
https://github.com/barnybug/cli53#wheres-pythonpypi-cli53
