### ISSUE TITLE
shortenName overzealously removes suffixes

### ISSUE THREAD

**Issue by adeodatus** [barnybug/cli53#221]
### Issue type

 - Bug report

### Steps to reproduce
call `shortenName("a.b.fineexample.com", "example.com")` 

### Expected behaviour
Shortens to `a.b.fineexample.com`

### Actual behaviour
Shortens to `a.b.fine`

### Have you checked if the documentation has the information you require?
n/a

### Could you contribute a fix or help testing with this issue?
```
func shortenName(name, origin string) string {
	if name == origin {
		return "@"
	}
	return strings.TrimSuffix(name, "."+origin)
}
```

**Comment by barnybug** [comment]
Thanks for reporting this.
Do you have an example zone file / command that demonstrates the issue which I could add to the tests?
