### ISSUE TITLE
dns : Not a TTL  error?

### ISSUE THREAD

**Issue by mofoster** [barnybug/cli53#222]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
0.8.8

### OS / Platform
Windows both 32 & 64bit

### Steps to reproduce
Trying to add a new a record as the example
cli53 rrcreate xxxxxx.com.au 'ww 60 A 122.202.65.214'

### Expected behaviour
Successful message return with new record been created 

### Actual behaviour
Error: dns: not a TTL: "'ww" at line: 2:3

### Have you checked if the documentation has the information you require?
Yes

**Comment by barnybug** [comment]
Sorry, but I couldn't reproduce this in the latest release.
I can't see any reason this wouldn't work with the command is exactly as typed.
