### ISSUE TITLE
cli53 call is hanging

### ISSUE THREAD

**Issue by BhanuCh** [barnybug/cli53#223]
### Issue type
 - Bug report
 

### cli53 version (cli53 --version)
0.8.5

### OS / Platform

Linux    4.4.35-33.55.amzn1.x86_64

### Steps to reproduce

we have over 15000 zones in one AWS account, we use one script that runs every day (export zone in BIND format)and commit to git. Few times the cli53 call was hanging and not returning even after 24 hours. As we know the limit for api calls is 5/sec but the cli53 should fail if it reaches rate limit. Instead it was hung.

is there a way to see on which api call cli53 was hung?

cli53 export <zone id>
is the command that  i run 15000 times in a loop.
it was hanging after successfully making 10000 requests

### Expected behaviour
cli53 command should fail if it reaches ratelimit.

### Actual behaviour
cli53 was hung

```
cli53 export <zone id>
```

### Have you checked if the documentation has the information you require?
no information in documentation.

### Could you contribute a fix or help testing with this issue?
yes

**Comment by barnybug** [comment]
Hi, cli53 does handle rate limiting gracefully (it will retry up to 100 times), and this would be tested as part of the test suite fairly heavily, so I suspect it's not that you are seeing.

You could try running with debug output 'cli53 export -d', though I'm not entirely sure knowing which command it is hanging will necessarily get us anywhere, you may at least be able to see if it is retrying.

Barnaby

**Comment by barnybug** [comment]
This issue looks like there hasn't been much activity on it. Closing, but please re-open if it still occurs.
