### ISSUE TITLE
is multi-value health-checked a-record support planned

### ISSUE THREAD

**Issue by BaconAndEggs** [barnybug/cli53#232]
### Issue type
 - Feature idea

### cli53 version (cli53 --version)
0.8.8

### OS / Platform
OSX

### Steps to reproduce
$ cli53 rrcreate -i multivalue_setid_1 --multivalue --health-check 2e668584-4352-4890-8ffe-6d3644702a1b example.com 'multiha 300 IN A 127.0.0.1'

### Expected behaviour
A single healthchecked multi-value record to be created

### Actual behaviour
(I made up the command example...)

### Have you checked if the documentation has the information you require?
I checked the base readme.md here, and tried to find the option in --help

### Could you contribute a fix or help testing with this issue?
I could help with manual testing, but probably not writing an automated test suite.

Great tool, thank you for providing this!  My apologies if this is already supported and I am just failing to find the option.

**Comment by barnybug** [comment]
Thanks for the feature request. Given my current time constraints, it's likely to be a while before I can look into this new functionality.

**Comment by lalinsky** [comment]
Implemented here - https://github.com/barnybug/cli53/pull/241
