### ISSUE TITLE
Add profile support

### ISSUE THREAD

**Issue by oojacoboo** [barnybug/cli53#233]
When working with multiple AWS accounts, it's necessary to define the keys you're wanting to use.  Does cli53 make use of the aws cli?  The profiles are stored at: `~/.aws/credentials`.  The AWS CLI supports the `--profile` flag for passing in the identifier for the profile to use.

**Comment by barnybug** [comment]
### Have you checked if the documentation has the information you require?

Please ensure you've checked: https://github.com/barnybug/cli53/blob/master/README.md
And also 'cli53 command --help' for the relevant command.

**Comment by oojacoboo** [comment]
I see it listed on the README now.  However, I first checked `--help` and I don't see anything there, which is what sparked this post.

```
NAME:
   cli53 - manage route53 DNS

USAGE:
   cli53 [global options] command [command options] [arguments...]

VERSION:
   0.8.8

COMMANDS:
     list, l       list domains
     create        create a domain
     delete        delete a domain
     import        import a bind zone file
     instances     dynamically update your dns with EC2 instance names
     export        export a bind zone file (to stdout)
     rrcreate, rc  create one or more records
     rrdelete, rd  delete a record
     rrpurge       delete all the records (danger!)
     dslist        list reusable delegation sets
     dscreate      create a reusable delegation set
     dsdelete      delete a reusable delegation set
     help, h       Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

**Comment by barnybug** [comment]
It's a specific option to commands, not a global option.
