### ISSUE TITLE
Please add CAA record support

### ISSUE THREAD

**Issue by AGWA** [barnybug/cli53#235]
### Issue type

 - Feature idea

### cli53 version (cli53 --version)

cli53 version 0.8.8

### OS / Platform

Linux

### Steps to reproduce

1. Add the following to a bind zone file named `sslmate.com`:

```
sslmate.com.  IN  CAA  0 issue "comodoca.com"
```

2. Run `cli53 import --file sslmate.com --replace --wait sslmate.com`

### Expected behaviour

The command completes successfully and adds the CAA record to sslmate.com.

### Actual behaviour

I get an "Unsupported resource record" error:

```
Error: Unsupported resource record: sslmate.com.        7200    IN      CAA     0 issue "comodoca.com"
```

### Have you checked if the documentation has the information you require?

Yes.

### Could you contribute a fix or help testing with this issue?

I can help test.

### Additional Resources

* Announcement of Route 53 CAA support: https://forums.aws.amazon.com/ann.jspa?annID=4799
* Route 53 CAA Documentation: http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#CAAFormat
* miekg/dns CAA documentation: https://godoc.org/github.com/miekg/dns#CAA
* CAA spec: https://tools.ietf.org/html/rfc6844

Thank you for cli53!

**Comment by barnybug** [comment]
Thanks for the feature request. Given my current time constraints, it's likely to be a while before I can look into this new functionality.
