### ISSUE TITLE
Binary wont run under Ubuntu extension on Windows10

### ISSUE THREAD

**Issue by hsiboy** [barnybug/cli53#236]
### Issue type

 - Bug report

### cli53 version (cli53 --version)
latest binary from repo
### OS / Platform
root@DLT9PYZTZ1:~# uname -a
Linux DLT9PYZTZ1 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

Download binary from repo, chmod, execute:

```
root@DLT9PYZTZ1:~# wget https://github.com/barnybug/cli53/releases/download/0.8.8/cli53-linux-amd64
root@DLT9PYZTZ1:~# chmod +x cli53-linux-amd64
root@DLT9PYZTZ1:~# file cli53-linux-amd64
cli53-linux-amd64.1: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, stripped

root@DLT9PYZTZ1:~# ./cli53-linux-amd64.1
bash: ./cli53-linux-amd64.1: cannot execute binary file: Exec format error
root@DLT9PYZTZ1:~#
```

### Expected behaviour

I'd expect the binary to run. As a test (because i'm aware its Ubuntu running inside windows), i downloaded the binary of terraform, and it runs just fine.
### Actual behaviour

as listed above

```

```

### Have you checked if the documentation has the information you require?
followed the instructions in Readme.md

**Comment by barnybug** [comment]
Hey - not sure why this would be the case. Suggest you use the Windows binary natively instead.

**Comment by hsiboy** [comment]
cute. but your S3 go binary runs just fine.

**Comment by barnybug** [comment]
Afraid I can't help you further - I don't have the platform to test on or isolate this issue. You'll have to determine yourself why there's the difference.

**Comment by hsiboy** [comment]
Quick question. Are you compiling on a MAC?

**Comment by barnybug** [comment]
No, travis compiles the release builds on Linux

**Comment by barnybug** [comment]
Closing this issue, as this platform is not a priority.
