### ISSUE TITLE
unable to build using go get

### ISSUE THREAD

**Issue by hsiboy** [barnybug/cli53#238]
### Issue type

 - Bug report

### cli53 version (cli53 --version)
latest
### OS / Platform

```
root@DLT9PYZTZ1:~# uname -a
Linux DLT9PYZTZ1 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to reproduce

run the commands to build from source as per instructions within the readme.md:

```
root@DLT9PYZTZ1:~# export GO15VENDOREXPERIMENT=1
root@DLT9PYZTZ1:~# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/.go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
root@DLT9PYZTZ1:~#
root@DLT9PYZTZ1:~# go get -v github.com/barnybug/cli53/cmd/cli53
root@DLT9PYZTZ1:~#
```

GO exits silently, note i used the --verbose flag, yet there is no output to cli. Nothing downloaded, nothing built.

### Expected behaviour

Expected go to build from the repo, as per the readme.md - Note, that this:
```go get -v github.com/barnybug/s3```
Builds just fine, and the binary runs just fine too!

### Actual behaviour

as above

**Comment by barnybug** [comment]
go 1.6 is pretty old now, suggest trying go 1.8.

**Comment by hsiboy** [comment]
tried with 1.9, same issue

```
root@DLT9PYZTZ1:~# go version
go version go1.9 linux/amd64
```

is the path right?

**Comment by barnybug** [comment]
ok, closing this now.
