### ISSUE TITLE
DNSSEC

### ISSUE THREAD

**Issue by adrianke** [barnybug/cli53#245]
### Issue type
 - Feature idea

### cli53 version (cli53 --version)
latest - 0.8.10

### OS / Platform
all

### Steps to reproduce
When importing from BIND, it would be nice to be able to support DNSSEC-types, like:
 - RRSIG
 - DNSKEY
 - CDNSKEY
 - CDS
 - NSEC

```
cli53 import --file dns.zone example.org
```

### Have you checked if the documentation has the information you require?
Yes. Also searched in the relevant parts of the code (bind.go)

### Could you contribute a fix or help testing with this issue?
I could help test, but not develop. Not fluent in Go.

**Comment by barnybug** [comment]
Sorry, not supported by route53.
https://aws.amazon.com/route53/faqs/#support_dnssec
