### ISSUE TITLE
Check if zone Name already exists

### ISSUE THREAD

**Issue by surrealchemist** [barnybug/cli53#246]
### Issue type
 - Feature idea

### cli53 version (cli53 --version)
cli53 version 0.8.10

I would find it helpful to have an option for cli53 to just exit if a zone already exists with the same name. It would make it easy to re-run a command to ensure the domain is there without having to have some other logic to manually check.

**Comment by barnybug** [comment]
Sticking to the unix philosophy, I would use cli53 list and grep. Not sure this warrants a whole new command.

**Comment by surrealchemist** [comment]
I was thinking more of just a flag to the create command so it skips creating if it exists.

Ended up doing something like this:

```
if ! cli53 export $domain > /dev/null 2>&1 ; then
    cli53 create $domain
fi
```

**Comment by barnybug** [comment]
I see - it is perfectly valid to create multiple domains for the same
domain name (you may have a private and public one, for instance). I think
given you can achieve it at least a couple of different ways, I wouldn't
consider adding this.
