### ISSUE TITLE
rrpurge fails it there's more than 1000 entries

### ISSUE THREAD

**Issue by reedobrien** [barnybug/cli53#248]
### Issue type

 - Bug report

### cli53 version (cli53 --version)
master @ c6c0c209ec3ac2be1b77fb6b05a869ba900f4e6c
### OS / Platform
linux

### Steps to reproduce
Get a domain add 1000s of records. Run
`cli53 rrpurge <domain> --confirm`

### Expected behaviour

The records to be purged.

### Actual behaviour

```cli53 rrpurge development.bepress.com --confirm
Error: InvalidChangeBatch: Number of records limit of 1000 exceeded.
	status code: 400, request id: 9bd4cd3c-b056-11e7-9c0c-79bb372e0092
```

```cli53 rrpurge development.bepress.com --confirm
Error: InvalidChangeBatch: Number of records limit of 1000 exceeded.
	status code: 400, request id: 9bd4cd3c-b056-11e7-9c0c-79bb372e0092
```

### Have you checked if the documentation has the information you require?
Yes

### Could you contribute a fix or help testing with this issue?
Maybe.

**Comment by barnybug** [comment]
Thanks for reporting this. Fixed in 0.8.12.
