### ISSUE TITLE
Skip Over Existing Records?

### ISSUE THREAD

**Issue by wykydtronik** [barnybug/cli53#249]
Hi I'm attempting to import a bulk file of records, I periodically have to do this from time to time.

I'm dealing with hundreds of records, and there's times where I might get a lot of conflicts where there is existing records.

Example:
----

cli53 import --file dec15imports.txt mydomain.com
Error: InvalidChangeBatch: Tried to create resource record set [name='marketing.mydomain.com.', type='A'] but it already exists
	status code: 400, request id: 35d0fc8b-e1dd-11e7-bdea-35724cb0a0a8

----

Naturally, you can go and remove the duplicate manually. But if there is 30-50 duplicate entries in a batch of 200 - this becomes tedious.

Is there a way to skip over existing records?

**Comment by barnybug** [comment]
`--replace`

**Comment by wykydtronik** [comment]
Thank you @barnybug

**Comment by wykydtronik** [comment]
Oops, --replace deleted the entire dns zonefile. I was attempting to add a small group of new DNS entries. I lost the entire zonefile. Thankfully I had a backup...

**Comment by barnybug** [comment]
Oops, you hadn't made it clear this was only part of the zone. `import --replace` is intended to be a complete zone file. This won't work on partial files, you need to give it a full zone file.

**Comment by wykydtronik** [comment]
Would it be possible to input a feature request for a skip duplicates? or perhaps update duplicates?

Thanks for looking, would be very handy.

**Comment by barnybug** [comment]
You can do this by single records using `cli53 rrcreate --replace`.

**Comment by wykydtronik** [comment]
Is this possible importing with --file?
