### ISSUE TITLE
Failover Policy using primary/secondary pair of health checked records gives "Error"

### ISSUE THREAD

**Issue by Tessando** [barnybug/cli53#252]
### Issue type

 - Bug report

### cli53 version (cli53 --version)
0.8.12 (cli53-windows-amd64)
### OS / Platform
Windows Server 2016
### Steps to reproduce

cli53 rrcreate -i Primary --failover PRIMARY --health-check 8b539753-xxxx-xxxx-xxxx-21890a632168 www.example.com 'ha 300 IN A 54.7.1.115'
cli53 rrcreate -i Secondary --failover SECONDARY www.example.com 'ha 300 IN A 54.7.1.117'
### Expected behaviour

I expected to be able to reverse my existing Failover Setup, effectively reversing the primary for "www.example.com" to the secondary. Instead I'm getting an error. 

Could this feature be for only "root" hosted zones (e.g. example.com) as opposed to "named" hosted zones (e.g. www.example.com)? If so, I should change the issue type to "Feature Request".
### Actual behaviour

```
Error: Zone 'www.example.com' not found
```

### Have you checked if the documentation has the information you require?

Yes, this was the closest command I could find that would perform what I'm trying to achieve. 
### Could you contribute a fix or help testing with this issue?
I can only offer testing at this point... I'm more Ops than "DevOps". :-)

**Comment by barnybug** [comment]
The error message simply indicates 'www.example.com' doesn't exist in your account. Is the domain definitely named this - what shows in `cli53 list`?

No reason this wouldn't work for subdomains.

**Comment by Tessando** [comment]
The domain does appear when I do the `cli53 list.` I did notice that when I do the `cli53 list` it does output `example.com.` with the trailing period. I just attempted that and am getting the same results (e.g. "Error: Zone 'www.example.com not found")

Now, that said, the `cli53 list` command just shows the hosted zone name (e.g. "example.com") because "**www**.example.com" is a name. So, when I look at the export of that hosted zone I see www	300	IN	A	54.7.1.115

Hopefully that makes sense. Thanks for the quick reply.

**Comment by barnybug** [comment]
Use the zone id instead (the long code starting Z...)

**Comment by barnybug** [comment]
I don't follow your explanation entirely though - if the domain is named 'example.com', that's what you need to use in the parameter `zone` to cli53. www is just a record in the domain judging by what you're saying.

**Comment by Tessando** [comment]
Okay, thanks.

You followed my thinking (even though I admit I could have been a little more clear). 

So, inside of the hosted zone I want to just change _just the subdomain_ (www.example.com) and leave the root record alone (e.g. example.com). 

Said another way: Is it possible to create the HealthCheck and Failover for a sub-domain instead of for the entire HostedZone itself?

Thank you again for your assistance. This is a very cool program and super handy for exporting my Hosted Zones. I appreciate it.

**Comment by barnybug** [comment]
Yes, you're creating a record `ha` (.example.com) in the above examples you give. Just change this to `www`.
