### ISSUE TITLE
beer file

### ISSUE THREAD

**Issue by jeremysimmons** [barnybug/cli53#253]
### Issue type
 - Feature idea

### cli53 version (cli53 --version)
0.8.12

### OS / Platform
Microsoft Windows [Version 10.0.16299.64]

### Steps to reproduce
view the root of source code repository on github

### Expected behaviour
a file named BEER.md or TIPS.md should exist indicating where to send $$ to buy the developer a pint.

### Actual behaviour
no file with that name existed 

### Have you checked if the documentation has the information you require?
yes

### Could you contribute a fix or help testing with this issue?
sure. what's the email address tied to your paypal account.

**Comment by barnybug** [comment]
Hey, thanks for the (most amusing) issue, but really I don't expect anything in return. It's enough if you go forth and tell everyone else about cli53 :-)
cheers!

**Comment by barnybug** [comment]
Tidying up old issues
