### ISSUE TITLE
Error with --profile

### ISSUE THREAD

**Issue by gordonwatson** [barnybug/cli53#254]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
0.8.12
### OS / Platform
Ubuntu 16.04
### Steps to reproduce
configure the ~/.aws folder with a valid credentials and config file like

credentials
```
[default]
aws_access_key_id = ACCESS_KEY
aws_secret_access_key = SECRET_KEY
```
config
```
[profile ops]
region=eu-west-1
role_arn = arn:aws:iam::111111111111:role/ops
source_profile = default
```

run:
`cli53 list --profile ops`

get the error:
```
Error: SharedCredsLoad: failed to get profile
caused by: section 'ops' does not exist
```

### Expected behaviour
should pull config then associated credentials

### Actual behaviour
get the error:

```
Error: SharedCredsLoad: failed to get profile
caused by: section 'ops' does not exist
```

### Have you checked if the documentation has the information you require?

Yes

### Could you contribute a fix or help testing with this issue?
Like to, just starting with Go tho :(
I'm guessing there's no stsAssume implemented...

**Comment by daygr** [comment]
@gordonwatson that error just looks like your config is wrong. The --profile option expects the profile's name, the 'profile' being implied. That is to say: `[profile ops]` should just be `[ops]`.

**Comment by gordonwatson** [comment]
Hi @daygr shouldn't be, the profile is configured correctly and works for aws cli, eb cli etc.

For comparison if I run cli53 then an aws cli command:

gordon@gordonXPS ~> cli53 list --profile ops
Error: SharedCredsLoad: failed to get profile
caused by: section 'hero-ops' does not exist
⤶
⤶
gordon@gordonXPS ~> aws ec2 describe-instances --profile ops
{
    "Reservations": [
        {
            "Instances": [
                {
                    "Monitoring": {

**Comment by daygr** [comment]
@gordonwatson Ah, my bad. I am wrong. The ~/.aws/config file does indeed expect [profile profilename] before config sections. I've spent a lot more time looking at the credentials files lately.

I think the issue you are hitting is not because of cli53, though. cli53 just uses the AWS golang SDK to initiate a session. This issue seems related: https://github.com/aws/aws-sdk-go/issues/472 which is closed but doesn't seem to have the resolution :frowning:

**Comment by gordonwatson** [comment]
Ahhh, good spot!  I was using a wrapper with Terraform but gave up as it's too clunky.  I didn't realise it was the underlying library.

I'd guess this will self resolve when (if?) the library get's fixed :(

I'll close off, thank you for looking at it!

**Comment by simher** [comment]
Hi,

I just rebuilt cli53 with the AWS_SDK_LOAD_CONFIG env variable set to true and now this is working for me.

Maybe rebuild and release cli53 with this set?

Best regards,
Simon

**Comment by gordonwatson** [comment]
+1 :)

**Comment by barnybug** [comment]
If someone could provide a PR for the required change, then I'll incorporate the necessary change.

**Comment by barnybug** [comment]
@simher from checking the docs, this environment variable influences runtime, not compile time, so I don't believe your comment is correct regarding recompiling - it's just you have this set at runtime too.
