### ISSUE TITLE
cli53 http proxy config

### ISSUE THREAD

**Issue by qhh0205** [barnybug/cli53#258]
### Issue type

 
 - Feature idea

### cli53 version (cli53 --version)
- cli53 version 0.8.12
### OS / Platform
- Mac OSX
### Issue
Does cli53 supports http proxy? Due to the high network latency, whenever i excute the command, it
will block for long time, so if cli53 supports the http proxy config, i can config the proxy to speed up access speed.

**Comment by barnybug** [comment]
Have you tried setting the environment variables `HTTP_PROXY` or `HTTPS_PROXY` - ie. the standard way to configure proxies?

I suspect this should work - if not then I'd suggest asking on the https://github.com/aws/aws-sdk-go - this is the library cli53 uses.

**Comment by qhh0205** [comment]
Ok, i set the `HTTP_PROXY` and `HTTPS_PROXY` env, i use the debug option, ex: `cli53 list --debug`       
 and can't  determine whether to aready use a proxy. Maybe I need to watch it for a while. 
 
Thanks!
