### ISSUE TITLE
What happened to rrlist?

### ISSUE THREAD

**Issue by jantman** [barnybug/cli53#259]
### Issue type

 - Feature idea

### cli53 version (cli53 --version)

0.8.12

### OS / Platform

Debian / VyOS

### Steps to reproduce

``cli53 rrlist <ZONE ID>``

### Expected behaviour

A list of records in the zone

### Actual behaviour

```
root@apt-er01:~# cli53 rrlist $ROUTE53_ZONE
No help topic for 'rrlist'
```

### Have you checked if the documentation has the information you require?

Yes, it's no longer documented.

### Could you contribute a fix or help testing with this issue?

No, I don't know Go.

### Some Discussion

My home router died two days ago, and I just got a new one. I'm following my install notes line-by-line, and had been using the Python-based ``cli53`` for dynamic DNS. I can't install the Python one anymore, and when I tried the new Go variant, it appears that there's no longer any functionality to list resource records in a zone...

**Comment by barnybug** [comment]
Use `cli53 export`.
