### ISSUE TITLE
Some zones don't seem to list right

### ISSUE THREAD

**Issue by apenney** [barnybug/cli53#261]
### Issue type
 - Bug report

### cli53 version (cli53 --version)

[I] cli53 --version
cli53 version master
(/usr//local/Cellar/cli53/0.8.12/bin/cli53)

### OS / Platform
OSX

### Steps to reproduce
When I do cli53 list I get the output from our ~600 zones.  Some of them, for some reason, don't display the associated domainname and I end up with output like:

ZZZZZZZZZZZZZ domain-name.com.
ZZ5ZK1LJGYU14

I noticed all my working ones have 14 character zone ids and all the broken ones have 12/13.  I did a run into JSON and it seemed like that worked.  Could I be getting some sort of API limit that gets silently ignored, or could I have stumbled over a weird bug?

**Comment by barnybug** [comment]
Hi, I've never seen anything like this.

I would need a reproduction case to get any further with fixing the issue.

**Comment by apenney** [comment]
Weirdly I found --format json worked every time, which is even weirder :O

**Comment by barnybug** [comment]
Can't progress this further without a reproduction case, so closing for now.
