### ISSUE TITLE
txt records without "" are imported wrong

### ISSUE THREAD

**Issue by weishenaustralia** [barnybug/cli53#263]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
0.8.10
### OS / Platform
ubuntu

### Steps to reproduce
DNS record: @       14400   IN      TXT     v=spf1 +a +mx -all
will be imported as @       14400   IN      TXT     "v=spf1" "+a" "+mx" "-all"

### Expected behaviour
expected to be @       14400   IN      TXT     "v=spf1 +a +mx -all"

### Actual behaviour
@       14400   IN      TXT     "v=spf1" "+a" "+mx" "-all"

### Have you checked if the documentation has the information you require?
YES

### Could you contribute a fix or help testing with this issue?
NO

**Comment by barnybug** [comment]
Hi, this behaviour comes from the dns parsing library that cli53 uses. It's widely deployed and the tests indicate without quotes this is the correct and expected behaviour:
https://github.com/miekg/dns/blob/master/parse_test.go#L396

So closing this, as I think it's behaving as expected.
