### ISSUE TITLE
"--Profile" option fails when using roles instead of Secret/ID

### ISSUE THREAD

**Issue by rszuster** [barnybug/cli53#264]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
cli53 version 0.8.12

### OS / Platform
Windows

### Steps to reproduce
I work on multiple accounts and i use roles for cross-account operations using a single set of credentials.
The credentials/config files look something  like this:

```
[default]
aws_access_key_id=<ID>
aws_secret_access_key=<SECRET>

[<profilename>]
role_arn=arn:aws:iam::<ACCT>:role/<ROLE>
source_profile=default
```

That configuration should be correct, it works just fine with AWS CLI, Powershell, etc, but cli53 throws the error shown below.

### Expected behaviour
```
cli53 list --profile <profilename>
ID             Name                 Record count Comment
<ID>           <name>               <records>
```

### Actual behaviour
```
cli53 list --profile <profilename>
Error: SharedCredsAccessKey: shared credentials <profilename> in C:\Users\<user>\.aws\credentials did not contain aws_access_key_id
caused by: error when getting key of section '<profilename>': key 'aws_access_key_id' not exists
```

**Comment by barnybug** [comment]
see: https://github.com/aws/aws-sdk-go/issues/472

**Comment by barnybug** [comment]
also: https://github.com/barnybug/cli53/issues/254
I don't have the time to test this setup, so if you could and provide further feedback.

**Comment by rszuster** [comment]
Setting the environment variable and rebuilding does yield a working binary.
```
set AWS_SDK_LOAD_CONFIG=1
go get github.com/barnybug/cli53/cmd/cli53
```

**Comment by gergnz** [comment]
I'm not sure that `AWS_SDK_LOAD_CONFIG` is required anymore. (there is some discussion in the go sdk community regarding it).

It looks like cli53 just needs to be built against a recent version of the SDK maybe? is it possibly to do a new release with an update SDK version?

**Comment by barnybug** [comment]
Yep, just required a new release on our part - up here:
https://github.com/barnybug/cli53/releases/tag/0.8.13
