### ISSUE TITLE
cli53 export fails if the hosted zone id length is 10.

### ISSUE THREAD

**Issue by BhanuCh** [barnybug/cli53#279]
### cli53 export failed.

 - Bug report

### cli53 version (cli53 --version)
   cli53 version 0.8.15
### OS / Platform
Mac os

### Steps to reproduce

cli53 export fails if the hosted zone id length is 10.

We do have server 100's hosted zones in route53. 
When i created a hosted zone couple of days back the hosted zone id length is only 10 where as other are greater than 10.

for this newly created hosted zone, cli53 export is failing.

cli53 export /hostedzone/ZEQ814LA8Y
Error: Zone '/hostedzone/ZEQ814LA8Y' not found

I found the bug, it is in

util.go line 102.
var reZoneId = regexp.MustCompile("^(/hostedzone/)?Z[A-Z0-9]{10,}$")

i think here you should check for length of 9 or more.

**Comment by barnybug** [comment]
Pull Request accepted!
