### ISSUE TITLE
Convert ALIAS records to CNAME

### ISSUE THREAD

**Issue by heydonovan** [barnybug/cli53#282]
### Issue type

Feature idea

### cli53 version (cli53 --version)

cli53 version master

### OS / Platform

macOS Mojave 10.14.6 (18G95)

### Steps to reproduce

We are trying to export all route53 records into BIND format so that we can import into Cloudflare. The final output leaves the ALIAS records which are not supported. Can we convert those to CNAME's?

**Comment by fleaz** [comment]
Just a quick heads up: Keep in mind that you can do things with an `ALIAS` what are not possible with a normal `CNAME` (that why they got invented ;) ).
You e.g. can't create a `CNAME` on your [domain apex](https://help.easyredir.com/en/articles/453072-what-is-a-domain-apex).

**Comment by barnybug** [comment]
As the previous commenter highlights, they're only superficially similar and not cross compatible, so converting them doesn't make sense.
