### ISSUE TITLE
Cannot be compiled without network connection

### ISSUE THREAD

**Issue by nkadel** [barnybug/cli53#288]
### Issue type

 - Bug report

### cli53 version (cli53 --version)
0.8.16

### OS / Platform
CentOS 7

### Steps to reproduce
Edit contrib/rpm/cli53.spec to match current release
    rpmbuile -bs  contrib/rpm/cli53.spec
    mock rpmbuild/SRPMS/cli53-0.8.15-1.87.el7.src.rpm

"mock" compilaton fails because mock does not permit network access during compilation.

### Expected behaviour

mock compilation should complete because golang is trying to pull in modules from github.com during compilation.

### Actual behaviour

The error message:

+ /usr/bin/rm -rf /builddir/build/BUILDROOT/cli53-0.8.15-1.87.x86_64
+ exit 0
Finish: rpmbuild src.rpm
Finish: build phase for src.rpm
INFO: Done(src.rpm) Config(default) 3 minutes 8 seconds
INFO: Results and/or logs in: /var/lib/mock/epel-7-x86_64/result
Finish: run
```

### Have you checked if the documentation has the information you require?

There is no published fix nor is the need for only local compilation mentioned.

### Could you contribute a fix or help testing with this issue?

I could test changes or help package RPM's in a suite to allow more secure and Fedora, RHEL, or EPEL compatible compilation. I do that for mock itself, Samba, awscli, and airflow. But I'm not a golang programmer and haven't tried building those up.

**Comment by barnybug** [comment]
I think this is a consideration for how you setup the SRPM, which isn't something I have control over. There's presumably ways to make go modules play nicely.
