### ISSUE TITLE
Does cli53 work behind a proxy?

### ISSUE THREAD

**Issue by Bibelo** [barnybug/cli53#290]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
cli53 version 0.8.16

### OS / Platform
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

### Steps to reproduce
HTTPS_PROXY=https://192.168.83.6:8080
https_proxy=https://192.168.83.6:8080
http_proxy=http://192.168.83.6:8080
HTTP_PROXY=http://192.168.83.6:8080

### Actual behaviour
It seems cli53 does not work behind a proxy.

cli53 list --debug

-----------------------------------------------------
DEBUG: Request route53/ListHostedZones Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /2013-04-01/hostedzone HTTP/1.1
Host: route53.amazonaws.com
User-Agent: aws-sdk-go/1.13.34 (go1.12.12; linux; 386)
(...)

### Have you checked if the documentation has the information you require?
yes

**Comment by barnybug** [comment]
According to this stackoverflow post, it should just work with HTTPS_PROXY:
https://stackoverflow.com/questions/51331169/how-can-i-use-a-https-proxy-with-amazon-go-library

**Comment by Bibelo** [comment]
It does not.

The presence of "Should work" in an answer is not a pertinent test.
