### ISSUE TITLE
Add `ls` command alias to `list` command

### ISSUE THREAD

**Issue by yermulnik** [barnybug/cli53#291]
### Issue type
 - Feature idea

### cli53 version (cli53 --version)
0.8.17

### OS / Platform
Linux Mint 18.3 Sylvia x86_64

### Steps to reproduce
`cli53-linux-amd64 ls`

### Expected behaviour
list domains

### Actual behaviour
```
> cli53-linux-amd64 ls
No help topic for 'ls'
```

### Have you checked if the documentation has the information you require?
yes

### Could you contribute a fix or help testing with this issue?
no (not familiar with Golang)

**Comment by barnybug** [comment]
Thanks for the feature request. I prefer a single canonical way to call commands, so this isn't something I'd consider adding, but thanks for the suggestion.
