### ISSUE TITLE
Documentation on providing credentials

### ISSUE THREAD

**Issue by DarkLogicX** [barnybug/cli53#303]
### Issue type

 - Documentation report

### OS / Platform
Windows 10 x64

### Steps to reproduce
I've just downloaded the cli53 app, and using info from this link.
https://www.theshell.guru/export-amazon-route-53-dns-hosted-zone-to-file/
It looks that I need to provide a credential file, while the info in the link is for linux, could you provide the info for doing the same on windows?

### Expected behaviour
Just a lack of documentation

```

### Have you checked if the documentation has the information you require?

<!--
  Please ensure you've checked: https://github.com/barnybug/cli53/blob/master/README.md
  And also 'cli53 command --help' for the relevant command.
  -->

### Could you contribute a fix or help testing with this issue?

**Comment by barnybug** [comment]
https://www.google.com/search?q=windows+aws+credentials+file should get you going. PRs welcome on a docs improvement.

**Comment by DarkLogicX** [comment]
Thanks, that worked.
So on windows you need to put a folder in your profile root (IE C:\Users\<Username>\.aws\) and put the text file there.

**Comment by barnybug** [comment]
Great, thanks.
