### ISSUE TITLE
BIND zone import automatically appending PTR value

### ISSUE THREAD

**Issue by rootbeerdan** [barnybug/cli53#305]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
cli53 version master

### OS / Platform
macOS Big Sur (Intel)

### Steps to reproduce

1. Exported BIND zone using `cli53 export --full 111.11.11.in-addr.arpa > example.com.txt`

2. Edited BIND zone file 
Example line configuration:

1.111.11.11.in-addr.arpa.	300	IN	PTR	rosalina.edge-dhcp.example.network
2.111.11.11.in-addr.arpa.	300	IN	PTR	luma.edge-dhcp.example.network

3. Saved file and imported zone file using `cli53 import --file example.com.txt --replace --wait 111.11.11.in-addr.arpa`

### Expected behaviour

Expected behavior would be a direct 1:1 import of the BIND file without any changes to the values

What records should look like:

1.111.11.11.in-addr.arpa.	300	IN	PTR	rosalina.edge-dhcp.example.network
2.111.11.11.in-addr.arpa.	300	IN	PTR	luma.edge-dhcp.example.network

### Actual behaviour

After import, all PTR values have been appended with the zone name

Example line configuration after import:

1.111.11.11.in-addr.arpa.	300	IN	PTR	rosalina.edge-dhcp.example.network.111.11.11.in-addr.arpa
2.111.11.11.in-addr.arpa.	300	IN	PTR	luma.edge-dhcp.example.network.111.11.11.in-addr.arpa

### Could you contribute a fix or help testing with this issue?

Yes, I am using this issue to track my progress

**Comment by anthonymf** [comment]
I just experienced this bug today.  Is there a reason why this was closed as not planned?
