### ISSUE TITLE
possible to create multiple NS records without import?

### ISSUE THREAD

**Issue by chrismccoy** [barnybug/cli53#312]
I know i can do replace, then append for the 2nd server, is there another way not using import?

**Comment by barnybug** [comment]
See `rrcreate`.

**Comment by chrismccoy** [comment]
can only create 1 ns record, not mutiple nameserver records, unless im missin sometnhing

**Comment by chrismccoy** [comment]
bascialy im creating zones for my own delegation set, so on creation, im replacing the 4 amazon dns servers with my own, and im currently doing it via replace for the first, and append for the other 3. was curious if there was a way to do all 4 on the orignal rrcreate --replace

**Comment by chrismccoy** [comment]
was able to figure it out by passing mutiple in 1 line

    cli53 rrcreate --replace $domain "@ 60 IN NS $dns1." "@ 60 IN NS $dns2." "@ 60 IN NS $dns3." "@ 60 IN NS $dns4."

**Comment by barnybug** [comment]
Great. A 'thank you' doesn't go amiss either :-)

**Comment by chrismccoy** [comment]
> Great. A 'thank you' doesn't go amiss either :-)

thanks :)
