### ISSUE TITLE
exec /usr/local/bin/cli53: exec format error

### ISSUE THREAD

**Issue by ghnp5** [barnybug/cli53#329]
### Issue type
Bug report

### cli53 version (cli53 --version)
0.8.22

### OS / Platform
Docker - debian

### Description

I'm looking to install this on Docker.

I see the `README` says I should use Debian instead of Alpine, or otherwise the builds won't work.

However, it doesn't seem to work for me (unless I'm doing something wrong!):

```
FROM debian:latest

RUN apt-get -y update \
 && apt-get upgrade -y \
 && apt-get dist-upgrade -y \
 && apt-get -y autoremove

RUN apt-get -y install openssl wget \
 && apt-get clean \
 && update-ca-certificates -f

RUN wget https://github.com/barnybug/cli53/releases/download/0.8.22/cli53-linux-amd64 -o /usr/local/bin/cli53 \
 && chmod +x /usr/local/bin/cli53

WORKDIR /opt/work/

ENTRYPOINT ["/usr/local/bin/cli53"]
CMD ["-v"]
```

When I run, I get:

> exec /usr/local/bin/cli53: exec format error

I tried the 3 linux builds available in the Releases.

Thank you!

**Comment by barnybug** [comment]
What does `ldd /usr/local/bin/cli53` show?

**Comment by ghnp5** [comment]
Alright... thank you very much.

I'm an idiot - I used `-o` instead of `-O` in `wget` :)

This works:

`wget https://github.com/barnybug/cli53/releases/download/0.8.22/cli53-linux-amd64 -O /usr/local/bin/cli53`

**Comment by barnybug** [comment]
Haha, thank you for coming clean on the mystery :-)
