### ISSUE TITLE
Relative CNAME targets

### ISSUE THREAD

**Issue by jorymil** [barnybug/cli53#68]
Amazon assumes that any domain name value you provide is fully qualified, and thus assumes a trailing dot, even if one is not provided in the Route 53 console.  When running cli53 export <zone>, cli53 does not make this assumption.

For example, if you have a CNAME alias called "alias" in the example.com zone with value "target.otherdomain.tld" (no trailing dot),  Amazon would respond with an answer of

alias.example.com.  IN  CNAME  target.otherdomain.tld.

Off the top of my head, I'm not sure if this goes against the RFCs or not.  At any rate, when running cli53 export, the above CNAME info would generate the following record:

alias IN CNAME target.otherdomain.tld

or with --full:

alias.example.com. IN CNAME target.otherdomain.tld

which, because it isn't fully qualified, means BIND would return a response of

alias.example.com.   <TTL>  IN  CNAME  target.otherdomain.tld.example.com.

Obviously a different response than Route 53 for the same data!

**Comment by markjreed** [comment]
Why was this closed with no comment?  I'm running into this issue now.  Route53 servers seem to be able to handle both actual relative CNAMEs and apparently-relative-but-really-meant-to-be-absolute CNAMEs; I'm guessing based on whether the record with $ORIGIN appended actually exists or not? But cli53 just spits them out without the trailing dot, which makes the resulting file not very useful in an actual BIND setup (or after BIND canonicalization).
