### ISSUE TITLE
Support for any ALIAS

### ISSUE THREAD

**Issue by delitescere** [barnybug/cli53#88]
As noted in http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html, ALIAS records can be used to alias resources other than ELB.

Current resources that can be aliased:
- CloudFront Distrbutions
- ELB
- S3 Website Endpoints
- Other Record Sets in the same Hosted Zone

cli53 currently only supports aliasing ELBs.

**Comment by Jeremlicious** [comment]
I had to export from route53 to Another DNS provider.
I replaced `AWS	ALIAS	A` BY `IN CNAME` in the BIND export file

**Comment by barnybug** [comment]
https://en.wiktionary.org/wiki/necro-bump#English :-)
