### ISSUE TITLE
error on export

### ISSUE THREAD

**Issue by sdunne** [barnybug/cli53#90]
This might be really ignorant of me, but I'm getting this error when doing an export.  I get about 25 records (out of 50) and then this:
Traceback (most recent call last):
  File "/usr/bin/cli53", line 10, in <module>
    main()
  File "/usr/lib/python2.6/site-packages/cli53/client.py", line 992, in main
    args.func(args, r53=connection)
  File "/usr/lib/python2.6/site-packages/cli53/client.py", line 610, in cmd_export
    zone.to_file(sys.stdout, relativize=not args.full)
  File "/usr/lib/python2.6/site-packages/dns/zone.py", line 503, in to_file
    relativize=relativize)
  File "/usr/lib/python2.6/site-packages/dns/node.py", line 53, in to_text
    print >> s, rds.to_text(name, **kw)
  File "/usr/lib/python2.6/site-packages/dns/rdataset.py", line 214, in to_text
    rd.to_text(origin=origin, relativize=relativize, **kw))
AttributeError: 'NoneType' object has no attribute 'to_text'

**Comment by barnybug** [comment]
Could you produce a minimal test case that demonstrates the issue please?

**Comment by ricardofelix** [comment]
hello, this is an issue that has to do with the evaluation of records on route53, it will fail there with this error when you try to export a zone that has record evaluation policy set to yes.

hope this helps.
cheers!

**Comment by ricardofelix** [comment]
also this seems to be related the same issue as reported on https://github.com/barnybug/cli53/issues/82

**Comment by okor** [comment]
For anyone reading this, you may not have enabled to proper permissions for your AWS User/Keys. You need to make sure that the User has either Route 53 access or Admin rights. Fixed it for me. A more descriptive error message would be helpful.

**Comment by ricardofelix** [comment]
interesting.. my script uses read-only permissions, default from AWS template, as I only want it to back up the records and I'm pretty sure it reads all the records just fine when I request it via API.
can you please give more info on your claims pls?

**Comment by khobbits** [comment]
I just tested this.

Running cli53 0.4.4

export and rrlist fails, when a 'failover' record exists.

The command works on my domains without failover, but traces on ones with.  I tried adding a failover record to a domain that was working, and then it stops working.

**Comment by barnybug** [comment]
covered by #92 which implements failover.
