### ISSUE TITLE
Record creation broken with identically-named private/public zones

### ISSUE THREAD

**Issue by bkeroackdsc** [barnybug/cli53#91]
When using private hosted zones (http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html) with a public zone of the same name, cli53 fails whether the zone identifier is supplied or not:

```
$ cli53 rrcreate --identifier "YYYYYYYYYYYYYY" internal.com test-cli53 A 10.10.0.0
usage: cli53 rrcreate [-h] [-x TTL] [-w WEIGHT] [-i IDENTIFIER]
                      [--region REGION] [-r] [--wait] [--dump]
                      zone rr {A,AAAA,CNAME,SOA,NS,MX,PTR,SPF,SRV,TXT,ALIAS}
                      values [values ...]```
cli53 rrcreate: error: argument zone: Zone 'internal.com' is ambiguous (matches: XXXXXXXXXXXXXX, YYYYYYYYYYYYYY), please specify ID
```

It is impossible to create records in either the public or private zone.

**Comment by dalekurt** [comment]
I'm also experiencing this issue, there is a private and public zone of the same name hosted on Route 53 and `cli53` fails regardless of the `HOSTED ZONE ID` is specified

Command executed
```console
/usr/local/bin/cli53 rrcreate my-domain.com my-server-name CNAME ec2-xx-xxx-xx-xxx.compute-1.amazonaws.com --ttl 300 --replace --wait --identifier "XXXXXXXXXXXXXX"
```

Output:
```console
cli53 rrcreate: error: argument zone: Zone 'my-domain.com' is ambiguous (matches: XXXXXXXXXXXXXX, YYYYYYYYYYYYYY), please specify ID
```

**Comment by dalekurt** [comment]
With some help I've got a solution to this issue.

Instead of providing the `ZONE` as `my-domain.com`, use the `Hosted Zone ID`,  use the command as follows:

```console
/usr/local/bin/cli53 rrcreate XXXXXXXXXXXXXX my-server-name CNAME ec2-xx-xxx-xx-xxx.compute-1.amazonaws.com --ttl 300 --replace --wait
```

**Comment by barnybug** [comment]
Have clarified this in the error message / docs.
