### ISSUE TITLE
Support route53 delegation sets

### ISSUE THREAD

**Issue by gergnz** [barnybug/cli53#94]
Depends on https://github.com/boto/boto/issues/3081

**Comment by barnybug** [comment]
Thanks very much for this! Will await the boto merge.

**Comment by jessekrembs** [comment]
Are still waiting on boto merge for this?

**Comment by gergnz** [comment]
@jessekrembs doesn't look like there has been any work on the boto side.

**Comment by barnybug** [comment]
Closing off stale issues
