### ISSUE TITLE
'xml' fails with cli53 0.4.4 on Amazon Linux with Python 2.6

### ISSUE THREAD

**Issue by whereisaaron** [barnybug/cli53#99]
I installed cli53 on Amazon Linux, which by default has Python 2.6 installed. I installed with:

```
yum install python-pip
pip install cli53
```

That works fine for commands like 'cli53 list' and 'cli53 export foo.com.' work fine, however 'cli53 xml foo.com.' fails with the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/cli53", line 10, in <module>
    main()
  File "/usr/local/lib/python2.6/site-packages/cli53/client.py", line 992, in main
    args.func(args, r53=connection)
TypeError: cmd_xml() got an unexpected keyword argument 'r53'
```

Does cli53 require python 3?

**Comment by barnybug** [comment]
Looks like you came across a bug in some under-used functionality. I'm not sure anyone uses 'cli53 xml', but should be easy to fix.
